(()=>{
'use strict';
const audit=window.REN_CHANNEL_AUDIT244,toolbar=document.getElementById('channelToolbar134');
const escape=esc;
const style=document.createElement('style');style.textContent=`
#channelToolbar134 .channel-options137 label{align-items:flex-start;gap:7px;position:relative;padding:10px 8px;grid-template-columns:18px 12px minmax(0,1fr) auto auto}
.channel-text244{min-width:0;flex:1;overflow-wrap:anywhere}.channel-text244 small{display:-webkit-box;-webkit-box-orient:vertical;-webkit-line-clamp:3;overflow:hidden;font-size:11px;font-weight:400;color:#687480;line-height:1.45;margin-top:4px}
.channel-info244{flex:0 0 auto;border:1px solid #cfc7ba;border-radius:50%;width:24px;height:24px;background:#fffdf7;color:#183248;font:600 14px Georgia;cursor:pointer}
#channelProof244{border:1px solid #cfc7ba;background:#faf7f0;color:#183248;padding:20px;width:min(650px,calc(100vw - 28px));max-height:85dvh;box-sizing:border-box;overflow:auto}
#channelProof244::backdrop{background:#162a405e}#channelProof244 h2{font:24px/1.2 Georgia;margin:0 35px 14px 0;overflow-wrap:anywhere}#channelProof244 p{font-size:14px;line-height:1.5}#channelProof244 a{overflow-wrap:anywhere}#channelProof244 summary{cursor:pointer;font-weight:600;line-height:1.5;padding:10px 0}#channelProof244 details{border-top:1px solid #d9d0c1}#channelProof244 button.close244{position:absolute;right:10px;top:10px;background:transparent;border:0;font-size:24px;cursor:pointer}
.channel-evidence244{border-left:3px solid #386c8e}.channel-evidence244 details summary{cursor:pointer}.channel-help244{font-size:11px;line-height:1.5;color:#687480}
@media(max-width:600px){#channelProof244{max-height:88dvh;padding:16px}.channel-text244 small{font-size:12px}}
`;document.head.append(style);
const heading=toolbar.querySelector('.channel-heading137 strong');if(heading)heading.textContent='Каналы и способы получения данных';
const help=toolbar.querySelector('.channel-help137');if(help){help.className='channel-help244';help.textContent='Выберите способ обмена для подсветки. Кнопка «i» показывает конкретный процесс и его источник. Тесты и эксперименты отмечены отдельно; фактический трафик не проверен.';}
const search=document.getElementById('channelSearch179');search.placeholder='Поиск системы или способа обмена…';search.setAttribute('aria-label','Поиск системы или способа обмена');
const byName=new Map(Object.entries(audit.catalog).map(([key,value])=>[value.name,{key,...value}]));
for(const row of toolbar.querySelectorAll('[data-channel-row179]')){const name=row.querySelector('input').value,spec=byName.get(name);if(!spec)continue;const text=row.querySelector('.channel-dot137').nextElementSibling;text.className='channel-text244';text.innerHTML=escape(name)+'<small>'+escape(spec.description)+'</small>';const info=document.createElement('button');info.type='button';info.className='channel-info244';info.textContent='i';info.setAttribute('aria-label','Основания канала: '+name);info.addEventListener('click',event=>{event.preventDefault();event.stopPropagation();openProof(spec.key);});row.append(info);}
const dialog=document.createElement('dialog');dialog.id='channelProof244';document.body.append(dialog);
function detailsFor(id,b){const e=DATA.edges.find(e=>e.id===id),r=e?.channel_research||{};return {...b,scope:r.scope||'',locator:r.locator||'',note:r.note||''};}
function sourceLinks(ids){return ids.map(id=>sourceById[id]).filter(Boolean).map(s=>'<p><a href="'+escape(s.url||'')+'" target="_blank" rel="noopener noreferrer">'+escape(s.title||s.source_id)+'</a>'+(s.actuality?'<br><small>'+escape(s.actuality)+'</small>':'')+'</p>').join('');}
function openProof(key){const spec=audit.catalog[key],records=Object.entries(audit.bindings).filter(([,b])=>b.keys.includes(key));dialog.innerHTML='<button class="close244" type="button" aria-label="Закрыть">×</button><h2 id="channelProofTitle244">'+escape(spec.name)+'</h2><p>'+escape(spec.description)+'</p><p><strong>Основания на главной карте: '+records.length+'</strong></p><p class="small">Ниже указаны конкретные процессы. Подключение ведомства к системе не означает обмен любыми данными со всеми её участниками.</p>'+records.map(([id,record])=>{const b=detailsFor(id,record),e=DATA.edges.find(e=>e.id===id);return '<details'+(records.length===1?' open':'')+'><summary>'+escape(e.a_name)+' — '+escape(e.b_name)+'</summary><p>'+escape(b.scope)+'</p><p><strong>Статус:</strong> '+escape(b.status)+'</p>'+(b.locator?'<p><strong>Где искать:</strong> '+escape(b.locator)+'</p>':'')+(b.note?'<p>'+escape(b.note)+'</p>':'')+sourceLinks(b.sourceIds)+'<p class="small">'+escape(id)+'</p></details>';}).join('');dialog.setAttribute('aria-labelledby','channelProofTitle244');dialog.querySelector('button').onclick=()=>dialog.close();dialog.scrollTop=0;dialog.showModal();}
const oldDetail=edgeDetail;edgeDetail=function(e){const record=audit.bindings[e.id];if(!record)return oldDetail(e);const b=detailsFor(e.id,record),names=b.keys.map(k=>audit.catalog[k].name);let html=oldDetail({...e,channels:names.join('; ')||'Способ доставки / получения не установлен'});html=html.replace(/<div class="card channel-evidence135">[\s\S]*?<\/div>/,'');const block='<div class="card channel-evidence244"><h4>Проверка канала · v244</h4><p><strong>'+escape(names.join('; ')||'Канал конкретной пары не установлен')+'</strong></p><p>'+escape(b.scope)+'</p><p>'+escape(b.status)+'</p>'+(b.locator?'<p><strong>Основание:</strong> '+escape(b.locator)+'</p>':'')+sourceLinks(b.sourceIds)+(b.rejected.length?'<details><summary>Почему прежние подписи не включены в фильтр</summary>'+b.rejected.map(r=>'<p><strong>'+escape(r.old)+':</strong> '+escape(r.reason)+'</p>').join('')+'</details>':'')+'</div>';const end=html.indexOf('</div>',html.indexOf('class="meta"'));return html.slice(0,end+6)+block+html.slice(end+6);};
window.renChannelAuditVersion='v244';
})();
