(()=>{
'use strict';
const p=window.ROSNEDRA_STAGE3,esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const regions=p.records.filter(n=>n.role==='REGIONAL_EXECUTIVE_AUTHORITY');
const flowTitles={'ROSNEDRA-REG47-REQUEST-001':'Проверка лицензии, экспертизы и регистрации работ','ROSNEDRA-REG47-ASLN-001':'Запись свидетельства об открытии месторождения в АСЛН'};
const label=n=>n.display_label||n.name;
window.rosnedraNavigate=function(nid){if(document.body.classList.contains('okur-active'))window.closeOkurLayer();openRosnedraStructure();selectNode(nid);document.getElementById('detail').parentElement.scrollTop=0;if(innerWidth<=1100){document.body.classList.add('detail-open');document.getElementById('detailToggle')?.setAttribute('aria-expanded','true');}};
const button=n=>'<button class="btn" data-rosnedra-node="'+esc(n.id)+'" onclick="rosnedraNavigate(\''+esc(n.id)+'\')">'+esc(label(n))+'</button>';
window.rosnedraNavigationHtml=function(nid){const relevant=nid===p.id||p.nodes.some(n=>n.id===nid);if(!relevant)return '';return '<div class="card rosnedra-navigation" data-rosnedra-navigation><h4>Роснедра · структура и регионы</h4><div class="rosnedra-shortcuts">'+(nid===p.id?'':button({id:p.id,name:'Вся структура'}))+regions.filter(n=>n.id!==nid).map(button).join('')+'</div><p class="small">Региональные органы имеют самостоятельные полномочия.</p></div>';};
window.rosnedraDataContractHtml=function(e){const c=e?.data_contract;if(!c)return '';return '<div class="card rosnedra-contract" data-data-contract="'+esc(e.id)+'"><h4>'+esc(c.title)+'</h4><p><strong>Отправитель:</strong> '+esc(e.a_name||e.aName)+'<br><strong>Получатель:</strong> '+esc(e.b_name||e.bName)+'</p><details><summary>Состав передаваемых данных</summary><ul>'+c.fields.map(x=>'<li>'+esc(x)+'</li>').join('')+'</ul></details><p><strong>Когда:</strong> '+esc(c.trigger)+'</p><p><strong>Срок:</strong> '+esc(c.deadline)+'</p><p class="small">'+esc(c.recipient_role)+'</p></div>';};
function reorganize(html,nid){if(nid!==p.id&&!p.nodes.some(n=>n.id===nid))return html;const t=document.createElement('template');t.innerHTML=html;if(t.content.querySelector('[data-rosnedra-navigation]'))return html;
 // Keep the overview compact and put region navigation before reference material.
 if(nid===p.id){for(const card of t.content.querySelectorAll('.card')){const title=card.querySelector('h4');if(!title)continue;if(['Центральный аппарат','Территориальные органы','Территориальные фонды геологической информации','Региональный орган · самостоятельные полномочия'].includes(title.textContent)){const section=document.createElement('details'),summary=document.createElement('summary');section.className='card rosnedra-directory';summary.textContent=title.textContent+' · '+card.querySelectorAll('button').length;section.append(summary);title.remove();while(card.firstChild)section.append(card.firstChild);card.replaceWith(section);}}}
 for(const card of t.content.querySelectorAll('.card')){const title=card.querySelector('h4');if(!title||!title.textContent.includes(' → '))continue;const e=p.edges.find(e=>title.textContent===e.a_name+' → '+e.b_name);if(!e)continue;const section=document.createElement('details'),summary=document.createElement('summary');section.className='card rosnedra-flow';section.dataset.rosnedraFlow=e.id;summary.textContent=flowTitles[e.id]||e.data_contract?.title||e.processes;section.append(summary);const direction=document.createElement('p');direction.className='small';direction.textContent=e.a_name+' → '+e.b_name;section.append(direction);title.remove();while(card.firstChild)section.append(card.firstChild);card.replaceWith(section);}
 const header=t.content.querySelector('.meta');if(header)header.insertAdjacentHTML('afterend',window.rosnedraNavigationHtml(nid));else t.content.insertBefore(document.createRange().createContextualFragment(window.rosnedraNavigationHtml(nid)),t.content.firstChild);
 return t.innerHTML;
}
const oldNode=nodeDetail;nodeDetail=function(nid){return reorganize(oldNode(nid),nid);};
const oldStructure=structureNodeDetail;structureNodeDetail=function(nid){return reorganize(oldStructure(nid),nid);};
const style=document.createElement('style');style.textContent='.rosnedra-shortcuts{display:flex;flex-wrap:wrap;gap:7px}.rosnedra-navigation,.rosnedra-directory,.rosnedra-flow,.rosnedra-contract{overflow-wrap:anywhere}.rosnedra-directory summary,.rosnedra-flow summary,.rosnedra-contract summary{cursor:pointer;font-weight:600;line-height:1.4}.rosnedra-directory .btn{white-space:normal;text-align:left;max-width:100%}.rosnedra-contract details{margin:10px 0}';document.head.append(style);
window.rosnedraStage10Ready=true;
})();
