(()=>{
'use strict';
const d=window.ROSNEDRA_MATRIX_V02,root='ORG-6DB46BA089',esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const nodes=new Map(d.nodes.map(n=>[n.id,n])),matrixEdges=new Map(d.edges.map(e=>[e.id,e]));
for(const s of d.sources){if(sourceById[s.source_id])Object.assign(sourceById[s.source_id],s);else{DATA.sources.push(s);sourceById[s.source_id]=s;}}
for(const n of d.nodes){if(nodeById[n.id])Object.assign(nodeById[n.id],n);else{DATA.nodes.push(n);nodeById[n.id]=n;}if(n.type==='ACTOR_CLASS')nodeById[n.id].map_visible=false;}
for(const e of d.edges){const old=DATA.edges.find(x=>x.id===e.id);if(old)Object.assign(old,e);else DATA.edges.push(e);}
const previousOverview=isOverviewEdge;isOverviewEdge=function(e){if(e.integration_layer==='ROSNEDRA_MATRIX_V02')return e.main_matrix_route||(!e.id.startsWith('RN26')&&previousOverview(e));return previousOverview(e);};
for(const e of window.ROSNEDRA_STAGE3.edges){if(matrixEdges.has(e.id))Object.assign(e,matrixEdges.get(e.id));}
const structural=d.edges.filter(e=>['STRUCTURAL_PART_OF','SUBORDINATE_ORGANIZATION'].includes(e.relation_types));
const parent=new Map(structural.map(e=>[e.b,e.a])),children=id=>structural.filter(e=>e.a===id).map(e=>nodes.get(e.b)).filter(n=>n&&n.type!=='ACTOR_CLASS');
let branch=root,internalMode=false;
nodes.get('RN26-COMMISSION-ETHICS').display_label='Комиссия по служебному поведению';nodes.get('RN26-CENTRAL-CORRUPTION').display_label='Профилактика коррупционных нарушений';
const internalEdges=d.edges.filter(e=>e.matrix_scope==='Внутреннее взаимодействие');
function navigate(id){if(graphMode==='STRUCTURE'&&structureMinistryFocusId===root&&id!==root&&!children(id).length)return selectNode(id);internalMode=false;branch=id;setGraphMode('STRUCTURE');structureDeptDetailId=null;structureMinistryFocusId=root;document.getElementById('structureMinistrySelect').value=root;startSimulation();fitStructureView();selectNode(id);document.getElementById('detail').parentElement.scrollTop=0;}
window.rosnedraInternalRelations=function(){focusSet.clear();contourLocalFocus133=null;structureDeptDetailId=null;selectedNode=null;selectedEdge=null;window.closeOkurLayer?.();document.body.classList.remove('atlas-home','atlas-internal-mode');setGraphMode('STRUCTURE');internalMode=true;branch=root;structureDeptDetailId=null;structureMinistryFocusId=root;startSimulation();fitStructureView();selectNode(root);};
document.addEventListener('click',ev=>{if(ev.target.closest('[onclick="rosnedraInternalRelations()"]')||(selectedNode===root&&ev.target.closest('[data-node-route="internal"]'))){ev.preventDefault();ev.stopImmediatePropagation();if(ev.target.closest('[data-node-route="internal"]'))window.openRosnedraStructure();else window.rosnedraInternalRelations();}},true);
window.rosnedraMatrixBranch=navigate;
window.openRosnedraStructure=function(){window.closeOkurLayer?.();document.body.classList.remove('atlas-home','atlas-internal-mode');focusSet.clear();contourLocalFocus133=null;structureDeptDetailId=null;selectedNode=null;selectedEdge=null;navigate(root);};
const beforeFocusMinistry=focusStructureMinistry;focusStructureMinistry=function(id){if(id===root)return graphMode==='STRUCTURE'&&structureMinistryFocusId===root&&branch!==root?selectNode(root):navigate(root);return beforeFocusMinistry(id);};
const beforeNavigate=window.rosnedraNavigate;window.rosnedraNavigate=function(id){if(nodes.has(id)){window.closeOkurLayer?.();document.body.classList.remove('atlas-home');return navigate(id);}return beforeNavigate(id);};

const ownPageSources={'ROSNEDRA-DEPT-SOLID':'RN26:solid','ROSNEDRA-DEPT-FINANCE':'RN26:finance','ROSNEDRA-DEPT-FLUIDS':'RN26:fluids','ROSNEDRA-DEPT-SCIENCE':'RN26:science','ROSNEDRA-DEPT-HR':'RN26:hr'};
const originalOwnSite=ownOfficialSiteForNode;ownOfficialSiteForNode=function(id){const n=nodes.get(id),url=n?.official_url||sourceById[ownPageSources[id]]?.url;if(n&&id!==root&&url)return {name:n.name,url};return originalOwnSite(id);};
const originalSites=officialSitesForNode;officialSitesForNode=function(id){if(nodes.has(id)&&id!==root&&(parent.has(id)||nodes.get(id).type==='DEPARTMENT'||nodes.get(id).type==='COLLEGIAL_BODY')){const own=ownOfficialSiteForNode(id);return own?[own]:[];}return originalSites(id);};
function nodeSourceCard(n){const source=sourceById[ownPageSources[n.id]||n.identity_source_id],url=source?.url||n.identity_source;if(!url)return '<div class="card node-source-card"><h4>Источник узла</h4><p>Источник создания узла не указан в матрице.</p></div>';return '<div class="card node-source-card"><h4>Источник узла</h4><p><a href="'+esc(url)+'" target="_blank" rel="noopener noreferrer">'+esc(source?.title||'Положение о Роснедрах')+'</a></p><p>'+esc(source?.what_confirms||'Основание существования и полномочия организации.')+'</p>'+(source?.actuality?'<p class="meta">'+esc(source.actuality)+'</p>':'')+'</div>';}

const beforeDepartment=focusDepartment;focusDepartment=function(id){if(structureMinistryFocusId===root&&nodes.has(id)){if(internalMode||branch!==root||!children(id).length)return selectNode(id);return navigate(id);}return beforeDepartment(id);};
function sourceLinks(ids){return (ids||[]).map(id=>sourceById[id]).filter(Boolean).map(s=>'<p><a href="'+esc(s.url)+'" target="_blank" rel="noopener">'+esc(s.title)+'</a></p>').join('');}
function nodeHtml(id){const n=nodes.get(id);if(!n)return '';const kids=internalMode?[]:children(id),related=d.edges.filter(e=>e.a===id||e.b===id),hierarchy=related.filter(e=>structural.includes(e)),processes=(internalMode?internalEdges.filter(e=>id===root||e.a===id||e.b===id):id===root?d.edges:related).filter(e=>!structural.includes(e));
return '<h2>'+esc(n.name)+'</h2><div class="meta">'+esc(({FEDERAL_AGENCY:'Федеральное агентство',DEPARTMENT:'Подразделение',FEDERAL_TERRITORIAL_BODY:'Территориальный орган',SUBORDINATE_ORGANIZATION:'Подведомственное учреждение',COLLEGIAL_BODY:'Коллегиальный орган',SYSTEM:'Информационная система',REGIONAL_AUTHORITY:'Региональный орган'})[n.type]||n.type)+' · '+esc(id)+'</div><div class="card"><h4>'+ (internalMode?'Внутренние связи по матрице v02':'Структура по матрице v02')+'</h4><p>'+(internalMode?'12 внутренних связей: 5 записей об участии в заседании комиссии, представление финансовой информации руководству и 6 бюджетных процессов. Канал электронного обмена для них не установлен. Сплошные линии — документальные записи; пунктир — процессы, требующие проверки актуальности.':d.edges.length+' записей: пунктир — принадлежность подразделения или учреждения, сплошная линия — документальный процесс. Нажмите на узел, чтобы раскрыть его подразделения.')+'</p><button class="btn" onclick="rosnedraInternalRelations()">Документальные процессы · 12</button> <button class="btn" onclick="rosnedraMatrixBranch(\''+root+'\')">Вся структура</button> '+(id!==root&&kids.length?'<button class="btn" onclick="rosnedraMatrixBranch(\''+id+'\')">Показать эту ветвь</button>':'')+(parent.has(id)?' <button class="btn" onclick="rosnedraMatrixBranch(\''+parent.get(id)+'\')">Родительский узел</button>':'')+'</div>'+(kids.length?'<div class="card"><h4>Подразделения и учреждения · '+kids.length+'</h4>'+kids.map(n=>'<p><button class="btn" onclick="rosnedraMatrixBranch(\''+n.id+'\')">'+esc(n.name)+'</button></p>').join('')+'</div>':'')+nodeSourceCard(n)+'<details class="card"><summary>Документальные процессы и ограничения · '+processes.length+'</summary>'+processes.map(e=>'<details class="card" data-matrix-record="'+esc(e.id)+'"><summary>'+esc(e.processes)+'</summary><p>'+esc(e.a_name)+' → '+esc(e.b_name)+'</p><p><strong>Канал:</strong> '+esc(e.channels)+'</p><p><strong>Содержание:</strong> '+esc(e.matrix_content||e.data_texts?.join('; ')||e.processes)+'</p><p><strong>Начало процесса:</strong> '+esc(e.matrix_trigger||'Не установлено')+'</p><p><strong>Срок:</strong> '+esc(e.matrix_deadline||'Не установлен')+'</p><p><strong>Доказательность:</strong> '+esc(e.matrix_evidence||e.status)+'</p><p>'+esc(e.basis)+'</p><p><strong>Актуальность:</strong> '+esc(e.matrix_current||'Фактическая эксплуатация отдельно не подтверждена')+'</p><p>'+esc(e.evidence_locator)+'</p>'+sourceLinks(e.source_ids)+'<button class="btn" onclick="rosnedraMatrixEdge(\''+e.id+'\')">Карточка процесса</button></details>').join('')+'</details>';
}
window.rosnedraMatrixEdge=id=>{const e=matrixEdges.get(id);if(e){selectedNode=null;selectEdge(e);}};
const beforeNode=nodeDetail;nodeDetail=function(id){let html=beforeNode(id);if(id!==root)return html;const t=document.createElement('template');t.innerHTML=html;for(const h of t.content.querySelectorAll('h4'))if(h.textContent==='Структура и региональные процессы')h.closest('.card').remove();return t.innerHTML+'<div class="card"><h4>Матрица Роснедр v02</h4><p>8 новых внешних потоков с документированным каналом. Подразделения раскрываются по ветвям. Перспективные, исторические и неподтверждённые маршруты доступны отдельно.</p><button class="btn primary" onclick="rosnedraMatrixBranch(\''+root+'\')">Структура и все записи матрицы</button></div>';};
const beforeStructureNode=structureNodeDetail;structureNodeDetail=function(id){if(nodes.get(id)?.type==='REGIONAL_AUTHORITY')return beforeStructureNode(id);if(nodes.has(id))return nodeHtml(id)+(window.rosnedraNavigationHtml?.(id)||'')+(window.rosnedraGeologicalAccessHtml?.((window.ROSNEDRA_STAGE3.geological_access_profiles||[]).filter(a=>a.node_ids.includes(id)))||'');return beforeStructureNode(id);};
const beforeBuild=buildStructureGraph;buildStructureGraph=function(){if(structureMinistryFocusId!==root)return beforeBuild();
 if(internalMode){const ids=new Set([root,...internalEdges.flatMap(e=>[e.a,e.b])]),visible=[...ids].map(id=>nodes.get(id)).filter(Boolean).map(n=>({...n,type:n.id===root?'MINISTRY':'DEPARTMENT',documentary_type:n.type,parentOrg:root,structure:true}));structureNodeById.clear();visible.forEach(n=>structureNodeById.set(n.id,n));return {nodes:visible,links:internalEdges.map(e=>({...e,kind:'ROSNEDRA_MATRIX_RECORD',kind_label:e.matrix_evidence||'Внутренний процесс'}))};}
 const ids=new Set([root,branch]);let ancestor=branch;while(parent.has(ancestor)){ancestor=parent.get(ancestor);ids.add(ancestor);}children(branch).forEach(n=>ids.add(n.id));
 if(branch===root){d.edges.filter(e=>e.matrix_scope==='Внутреннее взаимодействие'&&e.map_action==='Добавить с документальным статусом').forEach(e=>{if(nodes.get(e.a)?.type!=='ACTOR_CLASS')ids.add(e.a);if(nodes.get(e.b)?.type!=='ACTOR_CLASS')ids.add(e.b);});['ROSNEDRA-TERR-SZFO','REGION-47-NATURE-COMMITTEE','SYS-2F5732BB50'].forEach(id=>ids.add(id));}
 const visible=[...ids].map(id=>nodes.get(id)||nodeById[id]).filter(n=>n&&n.type!=='ACTOR_CLASS').map(n=>({...n,documentary_type:n.type,type:n.id===root?'MINISTRY':'DEPARTMENT',parentOrg:root,structure:true}));structureNodeById.clear();visible.forEach(n=>structureNodeById.set(n.id,n));const actual=new Set(visible.map(n=>n.id));
 const links=d.edges.filter(e=>actual.has(e.a)&&actual.has(e.b)&&(!e.id.startsWith('RN26')||structural.includes(e)||e.map_action==='Добавить с документальным статусом')).map(e=>({...e,kind:'ROSNEDRA_MATRIX_RECORD',kind_label:structural.includes(e)?'Организационная принадлежность':'Документальный процесс'}));return {nodes:visible,links};};
const beforeLayout=arrangeStructureLayout;arrangeStructureLayout=function(ns,es){if(structureMinistryFocusId!==root)return beforeLayout(ns,es);if(internalMode){const pos={'ORG-6DB46BA089':[620,70],'ROSNEDRA-DEPT-FINANCE':[210,380],'ROSNEDRA-DEPT-SOLID':[520,200],'ROSNEDRA-DEPT-FLUIDS':[520,420],'ROSNEDRA-DEPT-SCIENCE':[520,640],'RN26-COMMISSION-ETHICS':[960,330],'ROSNEDRA-DEPT-HR':[840,620],'RN26-CENTRAL-CORRUPTION':[1120,620]};ns.forEach(n=>Object.assign(n,{x:pos[n.id][0],y:pos[n.id][1]}));return;}const columns=4,width=Math.max(1280,W),cx=width/2;ns.find(n=>n.id===root)&&(Object.assign(ns.find(n=>n.id===root),{x:cx,y:75}));const rest=ns.filter(n=>n.id!==root);rest.forEach((n,i)=>Object.assign(n,{x:140+(i%columns)*(width-280)/(columns-1),y:205+Math.floor(i/columns)*112}));};
const beforeEdge=structureEdgeDetail;structureEdgeDetail=function(e){return e.kind==='ROSNEDRA_MATRIX_RECORD'?edgeDetail(e):beforeEdge(e);};
const beforeLabel=structureLabelLines;structureLabelLines=function(name,type,id){const n=nodes.get(id);return beforeLabel(n?.display_label||name,type,id);};
const beforeRender=renderStructureGraph;renderStructureGraph=function(){beforeRender();if(structureMinistryFocusId!==root)return;edgesLayer.querySelectorAll('.structure-ministry-boundary').forEach(e=>e.remove());nodesLayer.querySelectorAll('.structure-ministry-boundary-title,.structure-ministry-boundary-meta').forEach(e=>e.remove());for(const t of [...nodesLayer.children])if(t.tagName==='text')t.remove();const ns='http://www.w3.org/2000/svg',r=simulationNodes.find(n=>n.id===root),g=document.createElementNS(ns,'g');g.dataset.id=root;g.classList.add('node','ministry','core-ministry');g.setAttribute('transform',`translate(${r.x},${r.y})`);const circle=document.createElementNS(ns,'circle');circle.setAttribute('r','23');circle.setAttribute('fill',coreColor(root));const label=document.createElementNS(ns,'text');label.textContent='Роснедра';label.setAttribute('x','32');label.setAttribute('y','5');g.append(circle,label);g.addEventListener('click',()=>selectNode(root));nodesLayer.append(g);for(const line of edgesLayer.querySelectorAll('.edge.structure-edge')){const e=matrixEdges.get(line.dataset.id);if(e&&structural.includes(e)){line.style.stroke='#819099';line.style.opacity='.4';line.setAttribute('stroke-dasharray','4 5');}else{line.style.stroke='#346f91';line.style.strokeWidth='2';}}};

function drawInternalPaths(){if(!internalMode||structureMinistryFocusId!==root||graphMode!=='STRUCTURE')return;const ns='http://www.w3.org/2000/svg';edgesLayer.querySelectorAll('[data-rosnedra-internal-path]').forEach(el=>el.remove());for(const line of edgesLayer.querySelectorAll('line.structure-edge'))line.style.setProperty('display','none','important');for(const e of simulationEdges){const a=simulationNodes.find(n=>n.id===e.a),b=simulationNodes.find(n=>n.id===e.b),pending=e.map_action!=='Добавить с документальным статусом',reverse=simulationEdges.some(x=>x.a===e.b&&x.b===e.a),dx=b.x-a.x,dy=b.y-a.y,len=Math.hypot(dx,dy),bend=reverse?30:0;for(const hit of [true,false]){const p=document.createElementNS(ns,'path');p.dataset.id=e.id;p.dataset.rosnedraInternalPath='1';p.classList.add(hit?'edge-hit':'edge');p.setAttribute('d',`M${a.x} ${a.y} Q${(a.x+b.x)/2-dy/len*bend} ${(a.y+b.y)/2+dx/len*bend} ${b.x} ${b.y}`);p.setAttribute('fill','none');p.style.setProperty('stroke',hit?'transparent':pending?'#9b7751':'#346f91','important');p.style.setProperty('stroke-width',hit?'14px':'2.3px','important');p.style.setProperty('opacity','1','important');if(pending)p.setAttribute('stroke-dasharray','7 5');if(!hit)p.setAttribute('marker-end','url(#rosnedra-arrow)');p.addEventListener('mouseenter',ev=>showEdgeTooltip(e,ev));p.addEventListener('mousemove',moveTooltip);p.addEventListener('mouseleave',hideTooltip);p.addEventListener('click',ev=>{ev.stopPropagation();selectedNode=null;selectedEdge=e;detail.innerHTML=structureEdgeDetail(e);});edgesLayer.append(p);}}}
const beforeDrawPositions=drawStructurePositions;drawStructurePositions=function(){beforeDrawPositions();drawInternalPaths();};
const renderMatrix=renderStructureGraph;renderStructureGraph=function(){renderMatrix();if(internalMode&&structureMinistryFocusId===root){drawInternalPaths();document.getElementById('modeBadge').textContent='Внутренние связи Роснедр · матрица v02';const t=document.createElementNS('http://www.w3.org/2000/svg','text');t.setAttribute('x','80');t.setAttribute('y','760');t.style.fontSize='14px';t.textContent='Сплошные — документальные записи; пунктир — бюджетные процессы, требующие проверки актуальности';nodesLayer.append(t);}};
window.rosnedraMatrixState=()=>({branch,internalMode});window.ROSNEDRA_MATRIX_READY=true;startSimulation();
})();
