(()=>{
'use strict';
const p=window.ROSNEDRA_STAGE3,id=p.id,ns='http://www.w3.org/2000/svg';
const style=document.createElement('style');style.textContent='body.rosnedra-structure #graph .structure-dept,body.rosnedra-structure #graph .structure-edge,body.rosnedra-structure #graph .structure-dept text{display:initial!important}';document.head.append(style);
const oldMode=setGraphMode;setGraphMode=function(mode){if(mode!=='STRUCTURE')document.body.classList.remove('rosnedra-structure');return oldMode(mode);};
for(const n of p.nodes){if(!nodeById[n.id]){DATA.nodes.push(n);nodeById[n.id]=n;}else Object.assign(nodeById[n.id],n);}
for(const e of p.edges){Object.assign(e.channel_research,{conditional_channels:e.channel_research.conditional_channels||[],planned_channels:e.channel_research.planned_channels||[],date:e.channel_research.checked_on,locator:e.evidence_locator});if(!DATA.edges.some(x=>x.id===e.id))DATA.edges.push(e);}
for(const s of p.sources||[p.source]){if(!sourceById[s.source_id])DATA.sources.push(s);sourceById[s.source_id]=s;}
const oldOverview=isOverviewEdge;isOverviewEdge=function(e){if(e.id==='ROSNEDRA-REG47-ASLN-001')return false;if(e.integration_layer==='ROSNEDRA_REGIONAL_NORMATIVE')return true;return oldOverview(e);};
if(!coreIds.has(id)){CORE.push([id,'Роснедра']);coreIds.add(id);}
MINISTRY_SITES[id]={name:'Роснедра',url:'https://rosnedra.gov.ru/'};
for(const n of p.departments){const r={Dept_Global_ID:n.id,Org:'Роснедра',Registry_Name:n.name,Registry_Source:n.identity_source,Registry_Evidence:'Официальная структура центрального аппарата; распределение конкретных потоков по управлениям отдельно не установлено.'};structureDeptById.set(n.id,r);STRUCTURE_RAW.ownership_audit.push(r);}
if(p.verified_function){const r=p.verified_function;structureFunctionsByDept.set(r.Dept_Global_ID,[...(structureFunctionsByDept.get(r.Dept_Global_ID)||[]),r]);}
populateStructureFocusOptions();setFocusButtons();
const groups=[{title:'Центральный аппарат',nodes:p.departments},{title:'Территориальные органы',nodes:p.records.filter(n=>n.role==='FEDERAL_TERRITORIAL_BODY')},{title:'Территориальные фонды геологической информации',nodes:p.records.filter(n=>n.role==='GEOLOGICAL_INFORMATION_FUND')},{title:'Региональный орган · самостоятельные полномочия',nodes:p.records.filter(n=>n.role==='REGIONAL_EXECUTIVE_AUTHORITY')}];
// Cards explicitly distinguish membership evidence from documentary transmission.
const sourceLink=n=>'<a href="'+esc(n.identity_source)+'" target="_blank" rel="noopener">Источник</a>';
function overviewCard(){return '<div class="card"><h4>Структура и региональные процессы</h4><p>5 подразделений центрального аппарата, 10 территориальных органов и 7 геологических фондов. Три региональных органа показаны отдельно от федеральной структуры.</p><button class="btn primary" onclick="openRosnedraStructure()">Раскрыть структуру Роснедр</button><p class="small">Ленинградская, Псковская и Новгородская области: проекты перечней и решения территориального органа через АСЛН. Для Ленинградской области также предусмотрены запрос через СМЭВ и запись результата услуги. Фактическая эксплуатация отдельно не подтверждена; полная текущая редакция полномочий Новгородского министерства требует проверки.</p></div>';}
const oldNode=nodeDetail;nodeDetail=function(nid){return oldNode(nid)+(nid===id?overviewCard():'');};
const nodeBeforeAccess=nodeDetail;nodeDetail=function(nid){return nodeBeforeAccess(nid)+accessHtml(nid)+regionalEvidenceHtml(nid);};
function regionalEvidenceHtml(nid){const n=p.records.find(n=>n.id===nid&&n.role==='REGIONAL_EXECUTIVE_AUTHORITY');if(!n||n.region_code==='47')return '';return '<div class="card"><h4>Основание регионального маршрута</h4><p>'+esc(n.notes)+'</p><p>Проект перечня и ответ о согласовании направляются между региональным министерством и Севзапнедрами. Министерство имеет самостоятельные региональные полномочия.</p><a href="'+esc(n.competence_source)+'" target="_blank" rel="noopener">Полномочия регионального органа</a><p><a href="'+esc(n.territory_source)+'" target="_blank" rel="noopener">Территориальный охват Севзапнедр</a></p></div>';}
function accessHtml(nid){return (p.access_assessments||[]).filter(a=>a.node_ids.includes(nid)&&!(a.id==='ROSNEDRA-GEO-REG47-ACCESS'&&p.geological_access_profiles?.length)).map(a=>'<div class="card rosnedra-access" data-access-assessment="'+esc(a.id)+'"><h4>'+esc(a.title)+'</h4><p><strong>'+esc(a.status_label)+'</strong></p><p>'+esc(a.summary)+'</p><ul>'+a.items.map(x=>'<li>'+esc(x)+'</li>').join('')+'</ul><p class="small">'+esc(a.limitations)+'</p><p><strong>Для подтверждения обмена с комитетом:</strong> '+esc(a.required_proof)+'</p>'+a.source_ids.map(sid=>{const s=sourceById[sid];return '<p><a href="'+esc(s.url)+'" target="_blank" rel="noopener">'+esc(s.title)+'</a></p>';}).join('')+'</div>').join('')+window.rosnedraGeologicalAccessHtml((p.geological_access_profiles||[]).filter(a=>a.node_ids.includes(nid)));}
window.rosnedraGeologicalAccessHtml=function(profiles){const link=sid=>{const s=sourceById[sid];return s?'<a href="'+esc(s.url)+'" target="_blank" rel="noopener">'+esc(s.title)+'</a>':'';};return (profiles||[]).map(a=>'<div class="card rosnedra-geology" data-geological-profile="'+esc(a.id)+'"><h4>'+esc(a.title)+'</h4><div class="meta">'+esc(a.region)+' · общий порядок доступа</div><p>'+esc(a.summary)+'</p><p>'+esc(a.search)+'</p><p>'+link('ROSNEDRA:EFGI:DESCRIPTION')+'</p>'+a.routes.map(r=>'<details data-geological-route="'+esc(r.id)+'"><summary>'+esc(r.title)+'</summary><p><strong>Когда:</strong> '+esc(r.condition)+'</p><p><strong>Кто предоставляет:</strong> '+esc(r.provider)+'</p><p><strong>Действия:</strong> '+esc(r.action)+'</p><p><strong>Результат:</strong> '+esc(r.result)+'</p><p><strong>Срок:</strong> '+esc(r.deadline)+'</p><p class="small">'+esc(r.basis)+'</p>'+link(r.source_id)+'</details>').join('')+'<details data-geological-application><summary>'+esc(a.application_title)+'</summary><ul>'+a.application_fields.map(x=>'<li>'+esc(x)+'</li>').join('')+'</ul>'+link(a.application_source_id)+'</details><details><summary>'+esc(a.uses_label)+'</summary><ul>'+a.uses.map(x=>'<li>'+esc(x)+'</li>').join('')+'</ul></details><p>'+a.boundaries.map(esc).join('</p><p>')+'</p><p class="small">'+esc(a.proof_required)+'</p></div>').join('');};
style.textContent+=' .rosnedra-geology{overflow-wrap:anywhere}.rosnedra-geology details{margin:12px 0;padding:10px 0;border-top:1px solid #d8cec0}.rosnedra-geology summary{cursor:pointer;font-weight:600;line-height:1.4}';
window.openRosnedraStructure=function(){document.body.classList.remove('atlas-home');setGraphMode('STRUCTURE');focusStructureMinistry(id);};
const oldCard=structureNodeDetail;structureNodeDetail=function(nid){
 if(nid===id)return '<h2>Роснедра</h2><div class="meta">Федеральное агентство по недропользованию</div>'+overviewCard()+groups.map(g=>'<div class="card"><h4>'+esc(g.title)+'</h4>'+g.nodes.map(n=>'<p><button class="btn" onclick="selectNode(\''+n.id+'\')">'+esc(n.name)+'</button></p>').join('')+'</div>').join('')+'<p class="small">Пунктир обозначает принадлежность территориального органа. Фонды показаны по официальному перечню; конкретные потоки их обмена ещё не установлены. Сплошные стрелки — процессы, предусмотренные региональным регламентом.</p>';
 const n=p.nodes.find(x=>x.id===nid);if(!n)return oldCard(nid);
 const r=p.records.find(x=>x.id===nid),dept=p.departments.some(x=>x.id===nid);
 const role=dept?'Подразделение центрального аппарата':r?.role==='FEDERAL_TERRITORIAL_BODY'?'Территориальный орган федерального агентства':r?.role==='GEOLOGICAL_INFORMATION_FUND'?'Территориальный геологический фонд':n.type==='SYSTEM'?'Информационная система':'Региональный орган исполнительной власти';
 const flows=p.edges.filter(e=>e.a===nid||e.b===nid);
 return '<h2>'+esc(n.name)+'</h2><div class="meta">'+role+'</div><div class="card"><p>'+esc(r?.territory||'')+'</p><p>'+ (n.type==='REGIONAL_AUTHORITY'?'Региональный орган не является подразделением Роснедр.':dept?'Принадлежность подтверждена. Адресация конкретных запросов этому подразделению не установлена.':r?.role==='GEOLOGICAL_INFORMATION_FUND'?'Включён в официальный перечень фондов; обмен с комитетом не утверждается.':n.type==='SYSTEM'?'Комитет записывает результат услуги в систему. Отдельная передача этого результата Роснедрам не утверждается.':r?.territory_note||'Принадлежность подтверждена официальным перечнем. Территория указана по названию; подробное положение ещё требуется.')+'</p>'+sourceLink(n)+(r?.territory_source?'<p><a href="'+esc(r.territory_source)+'" target="_blank" rel="noopener">Территориальный охват</a></p>':'')+'</div>'+flows.map(e=>'<div class="card"><h4>'+esc(e.a_name)+' → '+esc(e.b_name)+'</h4><p>'+esc(e.processes)+'</p><p>'+esc(e.evidence_locator)+' · '+esc(e.channels)+'</p>'+contractHtml(e)+'<p class="small">Предусмотрено нормативным документом; эксплуатация отдельно не подтверждена.</p>'+e.sources.map(s=>'<p><a href="'+esc(s.url)+'" target="_blank" rel="noopener">'+esc(s.title)+'</a></p>').join('')+'</div>').join('');
};
function contractHtml(e){const c=e.data_contract;if(!c)return '';return '<h4>'+esc(c.title)+'</h4><ul>'+c.fields.map(x=>'<li>'+esc(x)+'</li>').join('')+'</ul><p><strong>Начало процесса:</strong> '+esc(c.trigger)+'</p><p><strong>Срок:</strong> '+esc(c.deadline)+'</p><p class="small">'+esc(c.recipient_role)+'</p>';}
const structureBeforeAccess=structureNodeDetail;structureNodeDetail=function(nid){let html=structureBeforeAccess(nid);const f=p.verified_function;if(f&&nid===f.Dept_Global_ID){html=html.replace('Адресация конкретных запросов этому подразделению не установлена.','Подтверждена функция выдачи решения в предусмотренных случаях; конкретная передача комитету не подтверждена.');html+='<div class="card"><h4>Подтверждённая функция</h4><p>'+esc(f.Function)+'</p><p>'+esc(f.Basis)+'</p><a href="'+esc(f.Source)+'" target="_blank" rel="noopener">Официальная карточка услуги</a><p><button class="btn" onclick="focusDepartment(\''+f.Dept_Global_ID+'\')">Показать подтверждённую функцию</button></p></div>';}if(f&&nid==='STR:F:'+f.Dept_Global_ID+':'+f.Function_ID)html+='<div class="card"><p>'+esc(f.Evidence)+'</p><a href="'+esc(f.Source)+'" target="_blank" rel="noopener">Официальное основание функции</a></div>';return html+accessHtml(nid)+regionalEvidenceHtml(nid);};
const oldDataCard=edgeDetail;edgeDetail=function(e){return oldDataCard(e)+(e.data_contract?'<div class="card">'+contractHtml(e)+'<p class="small">'+esc(e.basis)+'</p></div>':'');};
window.rosnedraDocumentaryCasesHtml=function(cases){return (cases||[]).map(c=>'<div class="card rosnedra-case" data-documentary-case="'+esc(c.id)+'"><h4>Документальный пример · '+esc(c.title)+'</h4><p><strong>Исторический случай · '+esc(c.period)+'</strong></p><p>'+esc(c.summary)+'</p><details><summary>Какие сведения содержит документ</summary><ul>'+c.fields.map(f=>'<li>'+esc(f)+'</li>').join('')+'</ul></details><p class="small">Региональный участник в документе: '+esc(c.historical_region_party)+'.</p><p>'+esc(c.limitations)+'</p>'+c.sources.map(s=>'<p><a href="'+esc(s.url)+'" target="_blank" rel="noopener">'+esc(s.title)+'</a></p>').join('')+'</div>').join('');};
window.rosnedraRegionalReviewsHtml=function(reviews){return (reviews||[]).map(r=>'<div class="card" data-regional-review="'+esc(r.id)+'"><h4>'+esc(r.title)+'</h4><p>'+esc(r.summary)+'</p><p>'+esc(r.limitations)+'</p>'+r.source_ids.map(sid=>{const s=sourceById[sid];return '<p><a href="'+esc(s.url)+'" target="_blank" rel="noopener">'+esc(s.title)+'</a></p>';}).join('')+'</div>').join('');};
function documentaryNodeHtml(nid){return window.rosnedraDocumentaryCasesHtml((p.documentary_cases||[]).filter(c=>c.node_ids.includes(nid)))+window.rosnedraRegionalReviewsHtml((p.regional_reviews||[]).filter(r=>r.node_ids.includes(nid)));}
const nodeBeforeCases=nodeDetail;nodeDetail=function(nid){return nodeBeforeCases(nid)+documentaryNodeHtml(nid);};
const structureBeforeCases=structureNodeDetail;structureNodeDetail=function(nid){return structureBeforeCases(nid)+documentaryNodeHtml(nid);};
const edgeBeforeCases=edgeDetail;edgeDetail=function(e){return edgeBeforeCases(e)+window.rosnedraDocumentaryCasesHtml(e.documentary_cases);};
const oldBuild=buildStructureGraph;buildStructureGraph=function(){const state=oldBuild();if(structureMinistryFocusId!==id)return state;
 for(const n of [...p.records,p.nodes.find(n=>n.type==='SYSTEM')]){state.nodes.push({...n,structure:true});structureNodeById.set(n.id,state.nodes.at(-1));}
 for(const n of p.records.filter(n=>n.role==='FEDERAL_TERRITORIAL_BODY'))state.links.push({id:'ROS:MEMBER:'+n.id,a:id,b:n.id,a_name:'Роснедра',b_name:n.name,kind:'ROSNEDRA_MEMBERSHIP',kind_label:'Организационная принадлежность',direction:'UNDIRECTED_DOCUMENTED_GENERAL',source:n.identity_source,evidence:'Официальный перечень территориальных органов. Это не передача данных.'});
 state.links.push(...p.edges.map(e=>({...e,kind:'ROSNEDRA_DATA',kind_label:'Процесс, предусмотренный регламентом'})));return state;
};
const oldLayout=arrangeStructureLayout;arrangeStructureLayout=function(nodes,links){oldLayout(nodes,links);if(structureMinistryFocusId!==id)return;
 const map=new Map(nodes.map(n=>[n.id,n])),width=Math.max(W,1100),height=Math.max(H,760),cx=width*.49,cy=height*.33;
 Object.assign(map.get(id),{x:cx,y:cy});
 p.departments.forEach((n,i)=>Object.assign(map.get(n.id),{x:cx-80+(i%2)*155,y:cy-48+Math.floor(i/2)*61}));
 const terr=p.records.filter(n=>n.role==='FEDERAL_TERRITORIAL_BODY'),fund=p.records.filter(n=>n.role==='GEOLOGICAL_INFORMATION_FUND');
 terr.forEach((n,i)=>Object.assign(map.get(n.id),{x:140+(i%2)*190,y:height*.13+Math.floor(i/2)*87}));
 fund.forEach((n,i)=>Object.assign(map.get(n.id),{x:160+(i%4)*265,y:height*.72+Math.floor(i/4)*95}));
 Object.assign(map.get('ROSNEDRA-TERR-SZFO'),{x:width*.76,y:height*.13});
 p.records.filter(n=>n.role==='REGIONAL_EXECUTIVE_AUTHORITY').forEach((n,i)=>Object.assign(map.get(n.id),{x:width*.96,y:height*(.27+i*.16)}));
 Object.assign(map.get('SYS-2F5732BB50'),{x:width*.77,y:height*.57});
 nodes.filter(n=>n.type==='FUNCTION'||n.type==='PROCESS').forEach((n,i)=>Object.assign(n,{x:cx+70,y:height*.59+i*50}));
};
const oldLabel=structureLabelLines;structureLabelLines=function(name,type,nid){const n=p.nodes.find(n=>n.id===nid);if(!n)return oldLabel(name,type,nid);let text=n.display_label;if(!text&&n.role==='FEDERAL_TERRITORIAL_BODY')text=n.territory.split(';')[0].replace(' федеральный','');if(!text&&n.role==='GEOLOGICAL_INFORMATION_FUND')text='Фонд · '+(n.territory||n.name).split(';')[0].replace(' федеральный','');return oldLabel(text||name,type,nid);};
const oldEdge=structureEdgeDetail;structureEdgeDetail=function(e){if(e.kind==='ROSNEDRA_DATA')return edgeDetail(e);if(e.kind==='ROSNEDRA_MEMBERSHIP')return '<h2>'+esc(e.b_name)+'</h2><div class="meta">Организационная принадлежность</div><p>'+esc(e.evidence)+'</p><a href="'+esc(e.source)+'" target="_blank" rel="noopener">Официальный перечень</a>';return oldEdge(e);};
const oldRender=renderStructureGraph;renderStructureGraph=function(){oldRender();document.body.classList.toggle('rosnedra-structure',structureMinistryFocusId===id);if(structureMinistryFocusId!==id)return;
 document.getElementById('viewport').style.transformOrigin='0px 0px';document.getElementById('viewport').style.transformBox='view-box';
 const cx=simulationNodes.find(n=>n.id===id).x,cy=simulationNodes.find(n=>n.id===id).y;
 const boundary=edgesLayer.querySelector('.structure-ministry-boundary');boundary?.setAttribute('r','175');
 const title=nodesLayer.querySelector('.structure-ministry-boundary-title'),meta=nodesLayer.querySelector('.structure-ministry-boundary-meta');title?.setAttribute('y',cy-150);meta?.setAttribute('y',cy-130);if(meta)meta.textContent='Центральный аппарат · 5 подразделений';
 for(const line of edgesLayer.querySelectorAll('line.structure-edge')){const e=simulationEdges.find(e=>e.id===line.dataset.id);if(line.classList.contains('edge-hit'))continue;if(e?.kind==='ROSNEDRA_MEMBERSHIP'){line.setAttribute('stroke-dasharray','4 5');line.style.opacity='.24';}else if(e?.kind==='ROSNEDRA_DATA'){line.style.stroke='#346f91';line.style.strokeWidth='2.2';line.setAttribute('marker-end','url(#rosnedra-arrow)');}}
 // Separate the two directions between the same organizations without crossing the central apparatus.
 for(const e of simulationEdges.filter(e=>e.integration_layer==='ROSNEDRA_REGIONAL_NORMATIVE')){
  const a=simulationNodes.find(n=>n.id===e.a),b=simulationNodes.find(n=>n.id===e.b),bend=e.a==='ROSNEDRA-TERR-SZFO'?40:-40;
  for(const line of [...edgesLayer.querySelectorAll('line.structure-edge')].filter(n=>n.dataset.id===e.id))line.style.setProperty('display','none','important');
  for(const hit of [true,false]){const path=document.createElementNS(ns,'path');path.classList.add(hit?'edge-hit':'edge');path.dataset.id=e.id;path.setAttribute('d',`M${a.x} ${a.y} Q${(a.x+b.x)/2+bend} ${(a.y+b.y)/2} ${b.x} ${b.y}`);path.setAttribute('fill','none');path.style.stroke=hit?'transparent':'#8069a0';path.style.strokeWidth=hit?'10':'2.2';if(!hit)path.setAttribute('marker-end','url(#rosnedra-arrow)');path.addEventListener('click',event=>{event.stopPropagation();selectStructureEdgeById(e.id);});edgesLayer.append(path);}
 }
 if(!document.getElementById('rosnedra-arrow')){const defs=document.createElementNS(ns,'defs');defs.innerHTML='<marker id="rosnedra-arrow" markerWidth="8" markerHeight="8" refX="9" refY="3" orient="auto"><path d="M0,0 L0,6 L7,3 Z" fill="#346f91"/></marker>';edgesLayer.append(defs);}
 for(const [text,x,y] of [['Территориальные органы',70,Math.max(H,760)*.075],['Геологические фонды · состав по перечню',90,Math.max(H,760)*.66],['Региональные процессы · 3 области',Math.max(W,1100)*.73,Math.max(H,760)*.065]]){const t=document.createElementNS(ns,'text');t.textContent=text;t.setAttribute('x',x);t.setAttribute('y',y);t.style.fontSize='13px';t.style.fill='#506678';nodesLayer.append(t);}
};
const oldFit=fitStructureView;fitStructureView=function(){if(structureMinistryFocusId!==id)return oldFit();const box=document.getElementById('viewport').getBBox();scale=Math.min((W-40)/box.width,(H-100)/box.height)*.95;tx=20-box.x*scale;ty=75-box.y*scale;applyTransform();};
DATA.rosnedra_access_assessments=p.access_assessments||[];DATA.rosnedra_verified_functions=p.verified_function?[p.verified_function]:[];
DATA.rosnedra_documentary_cases=p.documentary_cases||[];DATA.rosnedra_regional_reviews=p.regional_reviews||[];DATA.rosnedra_geological_access_profiles=p.geological_access_profiles||[];
startSimulation();window.rosnedraStage3Ready=true;window.rosnedraStage4Ready=!!window.rosnedraStage4Data;window.rosnedraStage5Ready=!!window.rosnedraStage5Data;window.rosnedraStage6Ready=!!window.rosnedraStage6Data;window.rosnedraStage7Ready=!!window.rosnedraStage7Data;window.rosnedraStage8Ready=!!window.rosnedraStage8Data;window.rosnedraStage9Ready=!!window.rosnedraStage9Data;
})();
