(()=>{
 'use strict';
 const dataUrl=new URL('data.json?v=okur-3',document.currentScript.src),ns='http://www.w3.org/2000/svg';
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const canvas=document.getElementById('graph'),scene=document.getElementById('viewport'),nativeNodes=document.getElementById('nodesLayer'),nativeEdges=document.getElementById('edgesLayer'),detailPanel=document.getElementById('detail'),toolbar=document.getElementById('channelToolbar134');
 let data,loading,active=false,view='okur',selected=null,family=null,routeId=null,page=0,query='',canonical=[],snapshot,detailBackup,sourceEdges,domainConfig,model,domainId=null,bundleId=null,viewTransforms={};
 const byId=new Map(),sourceNode=new Map();
 const get=id=>document.getElementById(id),group=id=>data.groups.find(g=>g.id===id);
 const graph=document.createElementNS(ns,'g');graph.id='okur-network';graph.style.display='none';scene.append(graph);
 const comparison=document.createElementNS(ns,'g');comparison.id='okur-atlas-comparison';comparison.style.display='none';scene.append(comparison);
 const switcher=document.createElement('div');switcher.className='okur-switch';switcher.hidden=true;switcher.innerHTML='<div class="okur-switch-title">ОКУР · сеть предметных контуров</div><div class="okur-switch-buttons"><button type="button" class="btn" id="ok-atlas-view">Документальный атлас</button><button type="button" class="btn" id="ok-target-view">ОКУР</button><button type="button" class="btn" id="ok-return">Закрыть сравнение</button></div><div id="ok-domain-nav" class="okur-domain-nav"></div><div id="ok-map-status" class="small"></div>';canvas.parentElement.append(switcher);
 const controls=document.createElement('div');controls.id='ok-controls';controls.hidden=true;toolbar.append(controls);
 function capture(){if(simulationNodes.length!==87)return;canonical=simulationNodes.map(n=>({id:n.id,x:n.x,y:n.y}));sourceEdges=nativeEdges.cloneNode(true);sourceEdges.removeAttribute('id');sourceEdges.style.display='';sourceNode.clear();for(const node of nativeNodes.children)sourceNode.set(node.dataset.id,node.cloneNode(true));}
 capture();
 function filteredRoutes(){const bundle=bundleId&&model.bundles.find(b=>b.id===bundleId);return data.routes.filter(r=>(!selected||r.a===selected||r.b===selected)&&(!family||r.family===family)&&(!query||byId.get(r.a).name.toLocaleLowerCase('ru').includes(query)||byId.get(r.b).name.toLocaleLowerCase('ru').includes(query))&&(!domainId||model.member.get(r.a)===domainId||model.member.get(r.b)===domainId)&&(!bundle||bundle.routeIds.includes(r.id)));}
 function matchingNode(n){return (!family||n.families.includes(family))&&(!query||n.name.toLocaleLowerCase('ru').includes(query))&&(!domainId||model.member.get(n.id)===domainId);}
 function chooseDomain(id){domainId=id||null;bundleId=selected=routeId=null;page=0;query='';get('ok-search').value='';get('ok-select').value='';get('ok-domain').value=domainId||'';view='okur';render();fitContours(domainId);showDetails();}
 function chooseBundle(id){bundleId=id;domainId=selected=routeId=null;page=0;query='';get('ok-search').value='';get('ok-select').value='';get('ok-domain').value='';render();showDetails();}
 function chooseRoute(id){routeId=id;renderGraph();renderDetails();detailPanel.parentElement.scrollTop=0;showDetails();}
 function fitContours(id){const map=window.OKURDomainGraph.layout(model,W,H),c=id&&map.centres[id],bounds=c?{x:c.x-540,y:c.y-325,width:1080,height:650}:map.bounds;scale=Math.max(.08,Math.min(1.15,(W-55)/bounds.width,(H-160)/bounds.height));if(c&&window.innerWidth<=820)scale=Math.max(.65,scale);tx=W/2-scale*(bounds.x+bounds.width/2);ty=H/2+55-scale*(bounds.y+bounds.height/2);applyTransform();viewTransforms.okur={scale,tx,ty};}
 function showDetails(){if(window.innerWidth<=1100)document.body.classList.add('detail-open');}
 function chooseNode(id){selected=id||null;if(!selected){domainId=null;get('ok-domain').value='';}bundleId=routeId=null;page=0;query='';get('ok-search').value='';get('ok-select').value=selected||'';if(selected&&view==='okur'){domainId=model.member.get(selected);get('ok-domain').value=domainId;fitContours(domainId);if(window.innerWidth<=820){const p=window.OKURDomainGraph.layout(model,W,H).positions.get(selected);scale=Math.max(.88,scale);tx=W/2-p.x*scale;ty=H/2-p.y*scale;applyTransform();}}render();showDetails();}
 function chooseFamily(id){family=family===id?null:id;routeId=null;page=0;render();showDetails();}
 function setView(next){viewTransforms[view]={scale,tx,ty};view=next;const saved=viewTransforms[next];if(saved){scale=saved.scale;tx=saved.tx;ty=saved.ty;applyTransform();}else if(next==='okur')fitContours(domainId);render();}
 function controlsMarkup(){controls.innerHTML=`<div class="channel-heading137"><strong>ОКУР · настройки карты</strong><button class="btn" id="ok-clear">Сбросить</button></div><label for="ok-domain">Предметный контур</label><select id="ok-domain"><option value="">Все четыре контура</option>${domainConfig.domains.map(d=>`<option value="${d.id}">${esc(d.name)}</option>`).join('')}</select><label for="ok-search">Поиск участника</label><input type="search" class="channel-search179" id="ok-search" placeholder="Название узла…"><select id="ok-select" aria-label="Участник ОКУР"><option value="">Все 87 участников</option>${data.nodes.map(n=>`<option value="${esc(n.id)}">${esc(n.name)}</option>`).join('')}</select><div class="okur-families">${data.groups.map(g=>`<button type="button" class="btn okur-family" data-family="${g.id}" style="--okur-color:${g.color}" aria-pressed="false"><strong>${g.id} · ${esc(g.name)}</strong><span>${g.count} исходных связей · ${g.nodeCount} участников</span></button>`).join('')}</div><p class="small">Участники собраны в предметные контуры. Линии между контурами объединяют исходные процессы в проекты общих контрактов. Выберите пакет, чтобы раскрыть конкретные связи.</p><button class="btn" id="ok-example">Как упрощается взаимодействие</button><p class="small">ОКУР — предлагаемая архитектура. Подключения на карте не являются измерением количества действующих интеграций.</p>`;
 get('ok-domain').value=domainId||'';get('ok-domain').onchange=e=>chooseDomain(e.target.value);get('ok-search').oninput=e=>{query=e.target.value.toLocaleLowerCase('ru');selected=domainId=bundleId=null;get('ok-domain').value='';routeId=null;page=0;get('ok-select').value='';render();};get('ok-select').onchange=e=>chooseNode(e.target.value);get('ok-clear').onclick=()=>{selected=family=routeId=null;page=0;query='';get('ok-search').value='';get('ok-select').value='';domainId=bundleId=null;get('ok-domain').value='';render();if(view==='okur')fitContours(null);};controls.querySelectorAll('[data-family]').forEach(b=>b.onclick=()=>chooseFamily(b.dataset.family));get('ok-example').onclick=()=>{example();showDetails();};
 }
 function renderGraph(){window.OKURDomainGraph.render(graph,{model,sourceNode,W,H,selected,family,query,domainId,bundleId,routeId,chooseNode,chooseDomain,chooseBundle,chooseFamily,chooseRoute});}
 function render(){if(!active||!data)return;nativeNodes.style.display='none';nativeEdges.style.display='none';graph.style.display=view==='okur'?'':'none';comparison.style.display=view==='atlas'?'':'none';comparison.replaceChildren(sourceEdges.cloneNode(true));for(const n of data.nodes){const el=sourceNode.get(n.id)?.cloneNode(true);if(!el)continue;el.classList.add('okur-atlas-node');el.classList.toggle('dim',!matchingNode(n));el.classList.toggle('selected',n.id===selected);el.setAttribute('tabindex','0');el.setAttribute('role','button');el.setAttribute('aria-label',n.name);el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();chooseNode(n.id);}};comparison.append(el);}renderGraph();controls.querySelectorAll('[data-family]').forEach(b=>{b.classList.toggle('active',b.dataset.family===family);b.setAttribute('aria-pressed',b.dataset.family===family);});get('ok-atlas-view').classList.toggle('primary',view==='atlas');get('ok-target-view').classList.toggle('primary',view==='okur');get('ok-atlas-view').setAttribute('aria-pressed',view==='atlas');get('ok-target-view').setAttribute('aria-pressed',view==='okur');get('ok-map-status').textContent=view==='atlas'?'87 исходных узлов · 354 документальные связи':'87 участников · 4 контура · 6 межконтурных пакетов';renderDetails();}
 function renderDetails(){get('modeBadge').textContent=view==='atlas'?'Документальный атлас':'ОКУР';get('countBadge').textContent=view==='atlas'?'87 узлов · 354 связи':'87 участников · 4 контура';if(window.innerWidth<=1100&&!selected&&!family&&!routeId&&!domainId&&!bundleId)requestAnimationFrame(()=>{if(active&&!selected&&!family&&!routeId&&!domainId&&!bundleId)document.body.classList.remove('detail-open');});const n=byId.get(selected),g=family&&group(family),d=domainId&&model.domains.get(domainId),bundle=bundleId&&model.bundles.find(b=>b.id===bundleId),routes=filteredRoutes(),picked=data.routes.find(r=>r.id===routeId),pages=Math.max(1,Math.ceil(routes.length/10));page=Math.min(page,pages-1);let html=`<h2>${esc(n?.name||bundle&&'Общий контракт между контурами'||d?.name||g?.name||'Сеть предметных контуров')}</h2><div class="meta">${view==='atlas'?'Исходные связи':'Целевая архитектура'}</div>`;
 if(n)html+=`<p>Основное проектное место на карте: ${esc(model.domains.get(model.member.get(n.id)).name)}. Участник сохраняет собственные данные, права и решения; он может работать с продуктами нескольких предметных контуров.</p><p>${n.families.map(id=>`<button class="btn okur-chip" data-detail-family="${id}">${id} · ${esc(group(id).name)}</button>`).join('')}</p>`;else if(!g&&!d&&!bundle)html+='<p>Четыре равноправных контура: ресурсы; промышленность и инфраструктура; социальные данные и услуги; управление и финансы. В каждом применяются общие правила A1–A5.</p><p>124 исходных процесса находятся внутри контуров, 230 процессов объединены в шесть межконтурных пакетов. Это группировка процессов для проектов общих контрактов, а не измерение действующих интеграций или экономии.</p><p class="small">Состав контуров проектный. Он определяет расположение участников на карте, а не подчинение, полномочия или исключительное владение предметом. Владелец, получатель, канал и основания остаются в исходных карточках.</p>';
 if(d&&!n)html+=`<p>${esc(d.description)}</p><div class="card"><strong>Проектный контур · ${d.nodeCount} участников</strong><p>Внутри контура: ${d.localRoutes} исходных процессов. Все процессы с участием этого контура раскрываются ниже.</p><p class="small">${esc(domainConfig.note)}</p></div>`;
 if(bundle)html+=`<div class="card"><h3>${esc(model.domains.get(bundle.a).name)} ↔ ${esc(model.domains.get(bundle.b).name)}</h3><p>${routes.length} исходных процессов в выбранном пакете. Проект общего контракта описывает схемы и версии продуктов, права доступа, порядок публикации, подписки, доставки и аудит.</p><p>${data.groups.map(g=>{const count=routes.filter(r=>r.family===g.id).length;return count?g.id+' · '+esc(g.name)+': '+count:'';}).filter(Boolean).join('<br>')}</p><p class="small">Объединённая линия раскрывает все исходные пары; права каждого участника и документальные основания не объединяются автоматически.</p></div>`;
 if(g)html+=`<div class="card"><strong>${esc(g.action)}</strong><p>${esc(g.description)}</p></div>`;if(picked)html+=routeDetails(picked);
 html+=`<h3>Исходные процессы · ${routes.length}</h3><p class="small">Сохранены все 354 пары и их классификация. Объединение в один продукт требует проверки состава, версии, прав и актуальности данных.</p>${routes.slice(page*10,page*10+10).map(r=>`<button class="btn okur-route${r.id===routeId?' active':''}" data-route="${esc(r.id)}"><span class="small">${r.family} · ${esc(r.id)}</span><strong>${esc(r.aName)} ↔ ${esc(r.bName)}</strong><span>${esc(r.subject)}</span></button>`).join('')}<div class="okur-pages"><button class="btn" id="ok-prev" ${page===0?'disabled':''}>←</button><span class="small">${page+1} / ${pages}</span><button class="btn" id="ok-next" ${page===pages-1?'disabled':''}>→</button></div>`;
 detailPanel.innerHTML=html;detailPanel.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>{routeId=b.dataset.route;renderGraph();renderDetails();detailPanel.parentElement.scrollTop=0;showDetails();});detailPanel.querySelectorAll('[data-detail-family]').forEach(b=>b.onclick=()=>chooseFamily(b.dataset.detailFamily));get('ok-prev').onclick=()=>{page--;renderDetails();};get('ok-next').onclick=()=>{page++;renderDetails();};
 }
 function routeDetails(r){const e=r.evidence,grades={DOCUMENTED_TRANSPORT:'Канал описан источником',MULTIPLE_DOCUMENTED_TRANSPORTS:'Несколько документированных каналов',DOCUMENTED_TRANSPORT_SCOPED:'Канал подтверждён в ограниченной области',DOCUMENTED_SHARED_SYSTEM_CONTEXT:'Совместное использование системы',MULTIPLE_SHARED_SYSTEM_CONTEXTS:'Несколько общих систем',MULTI_CHANNEL_DOCUMENTED:'Разные каналы для разных потоков'};return `<div class="card okur-evidence"><h3>${r.family} · ${esc(r.subject)}</h3><p class="small">${esc(r.id)}</p><p>${esc(r.aName)} ↔ ${esc(r.bName)}. Обозначение пары не задаёт направление передачи.</p><p><strong>Формат:</strong> ${esc(r.format||'не установлен')}<br><strong>Канал:</strong> ${esc(e.channels.join(', ')||'не установлен')}<br>${esc(grades[e.grade]||'Ограничения подтверждения см. в источниках')}</p>${e.scope?`<p>${esc(e.scope)}</p>`:''}${e.note?`<p>${esc(e.note)}</p>`:''}<p class="small">${esc(e.date)} ${esc(e.environment)}</p><p class="small">${e.current2026?'Утверждение о работе в 2026 году ограничено указанным потоком.':'Фактическая работа этого канала в 2026 году здесь не подтверждена.'} Источники описывают исходную связь; ОКУР — предлагаемая архитектура.</p>${e.sources.filter(s=>/^https?:\/\//i.test(s.url||'')).map(s=>`<p><a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.title||s.id)}</a></p>`).join('')}</div>`;}
 function example(){detailPanel.innerHTML='<h2>Как работают предметные контуры</h2><div class="meta">Проект ОКУР · общие контракты</div><div class="card"><h3>Внутри контура</h3><p>Участники описывают продукты по согласованным схемам A1–A5. У каждого продукта сохраняются владелец, версия и разрешения.</p></div><div class="card"><h3>Между контурами</h3><p>Вместо повторного согласования одинаковых требований для отдельных ведомственных пар предлагается общий контракт: состав и схемы данных, условия использования, актуальность, доставка изменений и аудит.</p></div><div class="card"><h3>На карте</h3><p>Общий вид показывает шесть пакетов межконтурного обмена. Выбор пакета раскрывает конкретные процессы, участников, каналы и источники. Локальные связи остаются в своих контурах.</p></div><p class="small">124 локальных и 230 межконтурных процессов сохранены. Шесть пакетов не означают шесть подтверждённых технических интеграций. Снижение затрат требует проверки возможности общего контракта для каждого набора продуктов.</p><button class="btn" id="ok-example-back">Вернуться к карте</button>';get('ok-example-back').onclick=renderDetails;}
 async function open(){if(active){setView('okur');return;}try{loading=loading||Promise.all([dataUrl,new URL('domains.json?v=okur-3',dataUrl)].map(url=>fetch(url,{cache:'no-cache'}).then(r=>{if(!r.ok)throw Error('HTTP '+r.status);return r.json();})));[data,domainConfig]=await loading;model=window.OKURDomainGraph.prepare(data,domainConfig);if(data.nodes.length!==87||data.routes.length!==354)throw Error('Неполная база');data.nodes.forEach(n=>byId.set(n.id,n));capture();if(canonical.length!==87)throw Error('Не удалось получить расположение полной карты');
 const oldBox=scene.getBBox(),origin={x:oldBox.x+oldBox.width/2,y:oldBox.y+oldBox.height/2};snapshot={sceneStyle:scene.getAttribute('style'),body:document.body.className,transform:{scale,tx,ty},edgeDisplay:nativeEdges.style.display,nodeDisplay:nativeNodes.style.display,badges:['modeBadge','countBadge'].map(id=>({el:get(id),text:get(id)?.textContent}))};detailBackup=document.createDocumentFragment();while(detailPanel.firstChild)detailBackup.append(detailPanel.firstChild);active=true;view='okur';selected=family=routeId=domainId=bundleId=null;query='';page=0;viewTransforms={atlas:{scale,tx:tx+origin.x*(1-scale),ty:ty+origin.y*(1-scale)}};scene.style.transformOrigin='0px 0px';scene.style.transformBox='view-box';document.body.classList.add('okur-active');document.body.classList.remove('atlas-home','atlas-internal-mode','atlas-external-focus','channel-filter-open');switcher.hidden=false;controls.hidden=false;controlsMarkup();get('modeBadge').textContent='Сравнение с ОКУР';get('countBadge').textContent='87 участников · 4 контура';get('ok-domain-nav').innerHTML=domainConfig.domains.map(d=>`<button class="btn" data-nav-domain="${d.id}">${esc({resources:'Ресурсы',industry:'Инфраструктура',social:'Социальные',governance:'Управление'}[d.id])}</button>`).join('')+'<button class="btn" id="ok-all-domains">Все контуры</button>';get('ok-domain-nav').querySelectorAll('[data-nav-domain]').forEach(b=>b.onclick=()=>chooseDomain(b.dataset.navDomain));get('ok-all-domains').onclick=()=>chooseDomain(null);render();fitContours(null);
 }catch(error){loading=null;detailPanel.innerHTML=`<h2>Не удалось открыть ОКУР</h2><p>${esc(error.message)}</p>`;showDetails();}}
 function close(){if(!active)return;active=false;graph.style.display='none';comparison.style.display='none';nativeEdges.style.display=snapshot.edgeDisplay;nativeNodes.style.display=snapshot.nodeDisplay;switcher.hidden=true;controls.hidden=true;document.body.className=snapshot.body;if(snapshot.sceneStyle===null)scene.removeAttribute('style');else scene.setAttribute('style',snapshot.sceneStyle);detailPanel.replaceChildren(detailBackup);snapshot.badges.forEach(({el,text})=>{if(el)el.textContent=text;});if(location.hash==='#okur')history.replaceState(null,'',location.pathname+location.search);scale=snapshot.transform.scale;tx=snapshot.transform.tx;ty=snapshot.transform.ty;applyTransform();}
 get('ok-atlas-view').onclick=()=>setView('atlas');get('ok-target-view').onclick=()=>setView('okur');get('ok-return').onclick=close;
 document.querySelectorAll('[data-open-okur]').forEach(b=>b.onclick=()=>{history.replaceState(null,'','#okur');open();});
 canvas.addEventListener('click',e=>{if(!active||view!=='atlas')return;const node=e.target.closest('.okur-atlas-node');if(node){e.stopImmediatePropagation();chooseNode(node.dataset.id);return;}const edge=e.target.closest('#okur-atlas-comparison [data-id]');if(edge){e.stopImmediatePropagation();routeId=edge.dataset.id;renderGraph();renderDetails();showDetails();}},true);
 document.addEventListener('click',e=>{if(!active)return;if(e.target.closest('[data-atlas-mode],#atlasBackHome,#resetBtn'))close();},true);
 canvas.addEventListener('click',e=>{if(active&&e.target===canvas){e.stopImmediatePropagation();selected=routeId=domainId=bundleId=null;page=0;get('ok-select').value='';get('ok-domain').value='';render();}},true);
 get('atlasNodeSearchInput')?.addEventListener('input',e=>{if(!active)return;e.stopImmediatePropagation();query=e.target.value.toLocaleLowerCase('ru');get('ok-search').value=e.target.value;selected=routeId=domainId=bundleId=null;get('ok-domain').value='';page=0;render();},true);
 window.addEventListener('resize',()=>{if(active){requestAnimationFrame(()=>{capture();render();if(view==='okur')fitContours(domainId);});}else requestAnimationFrame(capture);});
 for(const [id,factor] of [['zoomIn',1.18],['zoomOut',1/1.18]]){const button=get(id),native=button.onclick;button.onclick=e=>{if(!active)return native?.call(button,e);scale=Math.max(.08,Math.min(3.2,scale*factor));applyTransform();};}
 canvas.addEventListener('wheel',e=>{if(!active)return;e.preventDefault();e.stopImmediatePropagation();const rect=canvas.getBoundingClientRect(),x=e.clientX-rect.left,y=e.clientY-rect.top,old=scale,next=Math.max(.08,Math.min(3.2,old*Math.exp(-e.deltaY*.0012)));tx=x-(x-tx)*next/old;ty=y-(y-ty)*next/old;scale=next;applyTransform();},{capture:true,passive:false});
 const centreButton=get('centerBtn'),nativeCentre=centreButton?.onclick;if(centreButton)centreButton.onclick=e=>{if(active&&view==='okur')fitContours(domainId);else nativeCentre?.call(centreButton,e);};
 const touches=new Map();let pinch=null,touchMoved=false;
 const point=e=>{const r=canvas.getBoundingClientRect();return {x:e.clientX-r.left,y:e.clientY-r.top};};
 canvas.addEventListener('pointerdown',e=>{if(!active||e.pointerType!=='touch')return;e.stopImmediatePropagation();touches.set(e.pointerId,point(e));touchMoved=false;if(touches.size===2){const [a,b]=[...touches.values()];pinch={distance:Math.hypot(a.x-b.x,a.y-b.y),x:(a.x+b.x)/2,y:(a.y+b.y)/2};}if(e.target===canvas)try{canvas.setPointerCapture(e.pointerId);}catch(_){}},{capture:true});
 canvas.addEventListener('pointermove',e=>{if(!active||e.pointerType!=='touch'||!touches.has(e.pointerId))return;e.stopImmediatePropagation();const previous=touches.get(e.pointerId),now=point(e);touches.set(e.pointerId,now);if(touches.size===1){const dx=now.x-previous.x,dy=now.y-previous.y;if(Math.abs(dx)+Math.abs(dy)>1){tx+=dx;ty+=dy;touchMoved=true;applyTransform();}}else{const [a,b]=[...touches.values()],distance=Math.hypot(a.x-b.x,a.y-b.y),x=(a.x+b.x)/2,y=(a.y+b.y)/2;if(pinch?.distance){const old=scale,next=Math.max(.08,Math.min(3.2,old*distance/pinch.distance));tx=x-(x-tx)*next/old+x-pinch.x;ty=y-(y-ty)*next/old+y-pinch.y;scale=next;touchMoved=true;applyTransform();}pinch={distance,x,y};}},{capture:true});
 const endTouch=e=>{touches.delete(e.pointerId);if(touches.size<2)pinch=null;};canvas.addEventListener('pointerup',endTouch,true);canvas.addEventListener('pointercancel',endTouch,true);
 canvas.addEventListener('click',e=>{if(active&&touchMoved){e.stopImmediatePropagation();touchMoved=false;}},true);
 window.addEventListener('hashchange',()=>{if(location.hash==='#okur')open();else close();});document.addEventListener('keydown',e=>{if(active&&e.key==='Escape')close();});if(location.hash==='#okur')open();
})();
