(()=>{
 'use strict';
 const dataUrl=new URL('data.json?v=okur-2',document.currentScript.src),ns='http://www.w3.org/2000/svg';
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const canvas=document.getElementById('graph'),scene=document.getElementById('viewport'),nativeNodes=document.getElementById('nodesLayer'),nativeEdges=document.getElementById('edgesLayer'),detailPanel=document.getElementById('detail'),toolbar=document.getElementById('channelToolbar134');
 let data,loading,active=false,view='okur',selected=null,family=null,routeId=null,page=0,query='',canonical=[],snapshot,detailBackup,extra=false,sourceEdges;
 const byId=new Map(),sourceNode=new Map();
 const get=id=>document.getElementById(id),group=id=>data.groups.find(g=>g.id===id);
 const graph=document.createElementNS(ns,'g');graph.id='okur-network';graph.style.display='none';scene.append(graph);
 const comparison=document.createElementNS(ns,'g');comparison.id='okur-atlas-comparison';comparison.style.display='none';scene.append(comparison);
 const switcher=document.createElement('div');switcher.className='okur-switch';switcher.hidden=true;switcher.innerHTML='<div class="okur-switch-title">Одна карта · два способа взаимодействия</div><div class="okur-switch-buttons"><button type="button" class="btn" id="ok-atlas-view">Документальный атлас</button><button type="button" class="btn" id="ok-target-view">ОКУР</button><button type="button" class="btn" id="ok-return">Закрыть сравнение</button></div><div id="ok-map-status" class="small"></div>';canvas.parentElement.append(switcher);
 const controls=document.createElement('div');controls.id='ok-controls';controls.hidden=true;toolbar.append(controls);
 function capture(){if(simulationNodes.length!==87)return;canonical=simulationNodes.map(n=>({id:n.id,x:n.x,y:n.y}));sourceEdges=nativeEdges.cloneNode(true);sourceEdges.removeAttribute('id');sourceEdges.style.display='';sourceNode.clear();for(const node of nativeNodes.children)sourceNode.set(node.dataset.id,node.cloneNode(true));}
 capture();
 function filteredRoutes(){return data.routes.filter(r=>(!selected||r.a===selected||r.b===selected)&&(!family||r.family===family)&&(!query||byId.get(r.a).name.toLocaleLowerCase('ru').includes(query)||byId.get(r.b).name.toLocaleLowerCase('ru').includes(query)));}
 function matchingNode(n){return (!family||n.families.includes(family))&&(!query||n.name.toLocaleLowerCase('ru').includes(query));}
 function showDetails(){if(window.innerWidth<=820)document.body.classList.add('detail-open');}
 function chooseNode(id){selected=id||null;routeId=null;page=0;query='';get('ok-search').value='';get('ok-select').value=selected||'';render();showDetails();}
 function chooseFamily(id){family=family===id?null:id;routeId=null;page=0;render();showDetails();}
 function setView(next){view=next;render();}
 function controlsMarkup(){controls.innerHTML=`<div class="channel-heading137"><strong>ОКУР · настройки карты</strong><button class="btn" id="ok-clear">Сбросить</button></div><label for="ok-search">Поиск участника</label><input type="search" class="channel-search179" id="ok-search" placeholder="Название узла…"><select id="ok-select" aria-label="Участник ОКУР"><option value="">Все 87 участников</option>${data.nodes.map(n=>`<option value="${esc(n.id)}">${esc(n.name)}</option>`).join('')}</select><div class="okur-families">${data.groups.map(g=>`<button type="button" class="btn okur-family" data-family="${g.id}" style="--okur-color:${g.color}" aria-pressed="false"><strong>${g.id} · ${esc(g.name)}</strong><span>${g.count} исходных связей · ${g.nodeCount} участников</span></button>`).join('')}</div><p class="small">Позиции, значки и масштаб общие для двух видов. Цвета A1–A5 описывают состав данных. Выберите узел, чтобы раскрыть его работу с функциями ОКУР.</p><button class="btn" id="ok-example">Как упрощается взаимодействие</button><p class="small">ОКУР — предлагаемая архитектура. Подключения на карте не являются измерением количества действующих интеграций.</p>`;
 get('ok-search').oninput=e=>{query=e.target.value.toLocaleLowerCase('ru');selected=null;routeId=null;page=0;get('ok-select').value='';render();};get('ok-select').onchange=e=>chooseNode(e.target.value);get('ok-clear').onclick=()=>{selected=family=routeId=null;page=0;query='';get('ok-search').value='';get('ok-select').value='';render();};controls.querySelectorAll('[data-family]').forEach(b=>b.onclick=()=>chooseFamily(b.dataset.family));get('ok-example').onclick=()=>{example();showDetails();};
 }
 function geometry(){const nearest=Math.min(...canonical.map(p=>Math.hypot((p.x-W/2)/245,(p.y-H/2)/195)));const factor=Math.min(1,nearest/1.24);return {factor,rx:245*factor,ry:195*factor};}
 function servicePositions(){const cx=W/2,cy=H/2,f=geometry().factor;return {A1:{x:cx-112*f,y:cy-85*f},A2:{x:cx+112*f,y:cy-85*f},A3:{x:cx-112*f,y:cy+90*f},A4:{x:cx+112*f,y:cy+90*f},A5:{x:cx,y:cy}};}
 function port(p){const {rx,ry}=geometry(),dx=p.x-W/2,dy=p.y-H/2,k=1/Math.max(.001,Math.hypot(dx/rx,dy/ry));return {x:W/2+dx*k,y:H/2+dy*k};}
 function line(a,b,attrs=''){return `<line x1="${a.x}" y1="${a.y}" x2="${b.x}" y2="${b.y}" ${attrs}/>`;}
 function renderGraph(){const positions=new Map(canonical.map(n=>[n.id,n])),services=servicePositions();
 const geom=geometry(),compact=geom.factor<.7;
 let edges=`<defs><marker id="okur-graph-arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto"><path d="M0 0L10 5L0 10z" fill="#9b845c"/></marker></defs><ellipse class="okur-contour" cx="${W/2}" cy="${H/2}" rx="${geom.rx}" ry="${geom.ry}"/><text class="okur-contour-label" x="${W/2}" y="${H/2-170*geom.factor}" text-anchor="middle">${compact?'ОКУР':'ОКУР · общие публикации и подписки'}</text>`;
 const picked=data.routes.find(r=>r.id===routeId);const routeNodes=picked?new Set([picked.a,picked.b]):null;
 for(const n of data.nodes){const pos=positions.get(n.id);if(!pos)continue;const dst=port(pos);const highlight=routeNodes?routeNodes.has(n.id):selected?n.id===selected:family||query?matchingNode(n):false;const dim=(family||query)&&!matchingNode(n)||(routeNodes&&!routeNodes.has(n.id));const color=highlight?(family?group(family).color:'#415e75'):'#74838a';edges+=`<g class="okur-connection${dim?' dim':''}" data-connection="${esc(n.id)}"><title>${esc(n.name)} · предлагаемое общее подключение; продукты и права уточняются по процессам</title>${line(pos,dst,`class="edge-hit okur-connection-hit" data-connection="${esc(n.id)}"`)}${line(pos,dst,`class="okur-link" stroke="${color}" stroke-width="${highlight?2.3:.9}" stroke-opacity="${highlight?.9:.32}"`)}<circle cx="${dst.x}" cy="${dst.y}" r="2.1" fill="${color}"/></g>`;}
 for(const [a,b] of [['A1','A2'],['A3','A2'],['A4','A2']])edges+=line(services[a],services[b],'class="okur-functional-link" marker-end="url(#okur-graph-arrow)"');for(const id of ['A1','A2','A3','A4'])edges+=line(services.A5,services[id],'class="okur-governance-link"');
 if(selected){const node=byId.get(selected),origin=port(positions.get(selected));for(const id of node.families.filter(id=>!family||id===family))edges+=line(origin,services[id],`class="okur-product-link" stroke="${group(id).color}"`);}
 if(picked){for(const id of [picked.a,picked.b])edges+=line(port(positions.get(id)),services[picked.family],`class="okur-product-link" stroke="${group(picked.family).color}"`);}
 graph.innerHTML=`<g id="okur-edges">${edges}</g><g id="okur-services"></g><g id="okur-participants"></g>`;
 const participants=get('okur-participants');for(const n of data.nodes){const pos=positions.get(n.id),original=sourceNode.get(n.id);if(!pos||!original)continue;const el=original.cloneNode(true);el.classList.remove('selected','dim','internal-origin','internal-occluded','core-selected','external-focus-selected');el.classList.add('okur-participant');el.dataset.node=n.id;el.setAttribute('transform',`translate(${pos.x},${pos.y})`);el.classList.toggle('selected',selected===n.id||routeNodes?.has(n.id)===true);el.classList.toggle('dim',!matchingNode(n)||(routeNodes&&!routeNodes.has(n.id)));el.setAttribute('tabindex','0');el.setAttribute('role','button');el.setAttribute('aria-label',n.name);const title=document.createElementNS(ns,'title');title.textContent=n.name+' · '+n.families.join(', ');el.append(title);el.onclick=e=>{e.stopPropagation();chooseNode(n.id);};el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();chooseNode(n.id);}};participants.append(el);}
 const labels=compact?{A1:['A1','Объекты'],A2:['A2','События'],A3:['A3','Документы'],A4:['A4','Показатели'],A5:['A5','Права']}:{A1:['A1 · Объекты','и реестры'],A2:['A2 · События','и подписки'],A3:['A3 · Документы','и версии'],A4:['A4 · Показатели','и расчёты'],A5:['A5 · Каталог','права и аудит']};get('okur-services').innerHTML=data.groups.map(g=>{const p=services[g.id],r=compact?10:16,offset=compact?15:22;return `<g class="node okur-service${family===g.id?' selected':''}" data-service="${g.id}" transform="translate(${p.x},${p.y})" role="button" tabindex="0" aria-label="${esc(g.id+' '+g.name)}"><title>${esc(g.description)}</title><rect x="${-r}" y="${-r}" width="${r*2}" height="${r*2}" rx="4" fill="#fffdf8" stroke="${g.color}" stroke-width="2"/><path d="M-8 -5H8M-8 0H8M-8 5H3" transform="scale(${compact?.65:1})" stroke="${g.color}" fill="none" stroke-width="2"/><text x="${offset}" y="-2" fill="${g.color}">${esc(labels[g.id][0])}<tspan x="${offset}" dy="13">${esc(labels[g.id][1])}</tspan></text></g>`;}).join('');graph.querySelectorAll('[data-service]').forEach(el=>{el.onclick=e=>{e.stopPropagation();chooseFamily(el.dataset.service);};el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();chooseFamily(el.dataset.service);}};});graph.querySelectorAll('.okur-connection-hit').forEach(el=>el.onclick=e=>{e.stopPropagation();chooseNode(el.dataset.connection);});
 }
 function render(){if(!active||!data)return;nativeNodes.style.display='none';nativeEdges.style.display='none';graph.style.display=view==='okur'?'':'none';comparison.style.display=view==='atlas'?'':'none';comparison.replaceChildren(sourceEdges.cloneNode(true));for(const n of data.nodes){const el=sourceNode.get(n.id)?.cloneNode(true);if(!el)continue;el.classList.add('okur-atlas-node');el.classList.toggle('dim',!matchingNode(n));el.classList.toggle('selected',n.id===selected);el.setAttribute('tabindex','0');el.setAttribute('role','button');el.setAttribute('aria-label',n.name);el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();chooseNode(n.id);}};comparison.append(el);}renderGraph();controls.querySelectorAll('[data-family]').forEach(b=>{b.classList.toggle('active',b.dataset.family===family);b.setAttribute('aria-pressed',b.dataset.family===family);});get('ok-atlas-view').classList.toggle('primary',view==='atlas');get('ok-target-view').classList.toggle('primary',view==='okur');get('ok-atlas-view').setAttribute('aria-pressed',view==='atlas');get('ok-target-view').setAttribute('aria-pressed',view==='okur');get('ok-map-status').textContent=view==='atlas'?'87 исходных узлов · 354 документальные связи':'87 исходных узлов · 5 функций ОКУР · общие подключения';renderDetails();}
 function renderDetails(){get('modeBadge').textContent=view==='atlas'?'Документальный атлас':'ОКУР';get('countBadge').textContent=view==='atlas'?'87 узлов · 354 связи':'87 участников · 5 функций';if(window.innerWidth<=820&&!selected&&!family&&!routeId)requestAnimationFrame(()=>{if(active&&!selected&&!family&&!routeId)document.body.classList.remove('detail-open');});const n=byId.get(selected),g=family&&group(family),routes=filteredRoutes(),picked=data.routes.find(r=>r.id===routeId),pages=Math.max(1,Math.ceil(routes.length/10));page=Math.min(page,pages-1);let html=`<h2>${esc(n?.name||g?.name||'ОКУР на карте атласа')}</h2><div class="meta">${view==='atlas'?'Исходные связи':'Целевая архитектура'}</div>`;
 if(n)html+=`<p>Ведомство сохраняет собственные данные и решения. Через общее подключение публикует согласованные продукты или получает разрешённые версии и изменения по подписке.</p><p>${n.families.map(id=>`<button class="btn okur-chip" data-detail-family="${id}">${id} · ${esc(group(id).name)}</button>`).join('')}</p>`;else if(!g)html+='<p>Участники расположены так же, как в документальном атласе. Переключайте два вида карты, чтобы сравнить прямые связи с общими публикациями и подписками.</p><p>У ОКУР пять отдельных функций. A1, A3 и A4 описывают продукты; A2 доставляет изменения подписчикам; A5 управляет каталогом, схемами, доступом и аудитом.</p><p class="small">Общее подключение участника показано до границы среды ОКУР. Выбор участника раскрывает его функции внутри среды. Линии архитектуры не устанавливают направление исходных передач и не доказывают измеренную экономию интеграций.</p>';
 if(g)html+=`<div class="card"><strong>${esc(g.action)}</strong><p>${esc(g.description)}</p></div>`;if(picked)html+=routeDetails(picked);
 html+=`<h3>Исходные процессы · ${routes.length}</h3><p class="small">Сохранены все 354 пары и их классификация. Объединение в один продукт требует проверки состава, версии, прав и актуальности данных.</p>${routes.slice(page*10,page*10+10).map(r=>`<button class="btn okur-route${r.id===routeId?' active':''}" data-route="${esc(r.id)}"><span class="small">${r.family} · ${esc(r.id)}</span><strong>${esc(r.aName)} ↔ ${esc(r.bName)}</strong><span>${esc(r.subject)}</span></button>`).join('')}<div class="okur-pages"><button class="btn" id="ok-prev" ${page===0?'disabled':''}>←</button><span class="small">${page+1} / ${pages}</span><button class="btn" id="ok-next" ${page===pages-1?'disabled':''}>→</button></div>`;
 detailPanel.innerHTML=html;detailPanel.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>{routeId=b.dataset.route;renderGraph();renderDetails();detailPanel.parentElement.scrollTop=0;showDetails();});detailPanel.querySelectorAll('[data-detail-family]').forEach(b=>b.onclick=()=>chooseFamily(b.dataset.detailFamily));get('ok-prev').onclick=()=>{page--;renderDetails();};get('ok-next').onclick=()=>{page++;renderDetails();};
 }
 function routeDetails(r){const e=r.evidence,grades={DOCUMENTED_TRANSPORT:'Канал описан источником',MULTIPLE_DOCUMENTED_TRANSPORTS:'Несколько документированных каналов',DOCUMENTED_TRANSPORT_SCOPED:'Канал подтверждён в ограниченной области',DOCUMENTED_SHARED_SYSTEM_CONTEXT:'Совместное использование системы',MULTIPLE_SHARED_SYSTEM_CONTEXTS:'Несколько общих систем',MULTI_CHANNEL_DOCUMENTED:'Разные каналы для разных потоков'};return `<div class="card okur-evidence"><h3>${r.family} · ${esc(r.subject)}</h3><p class="small">${esc(r.id)}</p><p>${esc(r.aName)} ↔ ${esc(r.bName)}. Обозначение пары не задаёт направление передачи.</p><p><strong>Формат:</strong> ${esc(r.format||'не установлен')}<br><strong>Канал:</strong> ${esc(e.channels.join(', ')||'не установлен')}<br>${esc(grades[e.grade]||'Ограничения подтверждения см. в источниках')}</p>${e.scope?`<p>${esc(e.scope)}</p>`:''}${e.note?`<p>${esc(e.note)}</p>`:''}<p class="small">${esc(e.date)} ${esc(e.environment)}</p><p class="small">${e.current2026?'Утверждение о работе в 2026 году ограничено указанным потоком.':'Фактическая работа этого канала в 2026 году здесь не подтверждена.'} Источники описывают исходную связь; ОКУР — предлагаемая архитектура.</p>${e.sources.filter(s=>/^https?:\/\//i.test(s.url||'')).map(s=>`<p><a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.title||s.id)}</a></p>`).join('')}</div>`;}
 function example(){const count=extra?5:4;detailPanel.innerHTML=`<h2>Одна публикация — несколько подписок</h2><div class="meta">Условный пример повторного использования</div><p>Нескольким ведомствам нужна одна разрешённая версия сведений ЕГРЮЛ. При раздельной подготовке источник создаёт одинаковую выдачу для каждого получателя; с ОКУР он публикует общую версию.</p><label><input type="checkbox" id="ok-extra" ${extra?'checked':''}> Добавить ещё одного получателя</label><div class="card"><h3>Раздельные выдачи</h3><strong class="okur-number">${count}</strong> подготовок одинаковых данных</div><div class="card"><h3>Публикации и подписки ОКУР</h3><strong class="okur-number">1</strong> общая публикация · ${count} разрешённых подписок<p>A1: объект и версия · A2: изменения · A5: права и аудит. Доставки и проверки прав сохраняются для каждого получателя.</p></div><p class="small">Повторное использование возможно при совпадении объекта, состава, версии и срока актуальности, если права допускают общий продукт. Источники не подтверждают, что в существующей системе выполняются четыре ручные подготовки: пример объясняет механизм ОКУР.</p><button class="btn" id="ok-example-back">Вернуться к карточке карты</button>`;get('ok-extra').onchange=e=>{extra=e.target.checked;example();};get('ok-example-back').onclick=renderDetails;}
 async function open(){if(active){setView('okur');return;}try{loading=loading||fetch(dataUrl,{cache:'no-cache'}).then(r=>{if(!r.ok)throw Error('HTTP '+r.status);return r.json();});data=await loading;if(data.nodes.length!==87||data.routes.length!==354)throw Error('Неполная база');data.nodes.forEach(n=>byId.set(n.id,n));capture();if(canonical.length!==87)throw Error('Не удалось получить расположение полной карты');
 snapshot={body:document.body.className,transform:{scale,tx,ty},edgeDisplay:nativeEdges.style.display,nodeDisplay:nativeNodes.style.display,badges:['modeBadge','countBadge'].map(id=>({el:get(id),text:get(id)?.textContent}))};detailBackup=document.createDocumentFragment();while(detailPanel.firstChild)detailBackup.append(detailPanel.firstChild);active=true;view='okur';document.body.classList.add('okur-active');document.body.classList.remove('atlas-home','atlas-internal-mode','atlas-external-focus','channel-filter-open');switcher.hidden=false;controls.hidden=false;controlsMarkup();get('modeBadge').textContent='Сравнение с ОКУР';get('countBadge').textContent='87 участников · 5 функций';render();
 }catch(error){loading=null;detailPanel.innerHTML=`<h2>Не удалось открыть ОКУР</h2><p>${esc(error.message)}</p>`;showDetails();}}
 function close(){if(!active)return;active=false;graph.style.display='none';comparison.style.display='none';nativeEdges.style.display=snapshot.edgeDisplay;nativeNodes.style.display=snapshot.nodeDisplay;switcher.hidden=true;controls.hidden=true;document.body.className=snapshot.body;detailPanel.replaceChildren(detailBackup);snapshot.badges.forEach(({el,text})=>{if(el)el.textContent=text;});if(location.hash==='#okur')history.replaceState(null,'',location.pathname+location.search);scale=snapshot.transform.scale;tx=snapshot.transform.tx;ty=snapshot.transform.ty;applyTransform();}
 get('ok-atlas-view').onclick=()=>setView('atlas');get('ok-target-view').onclick=()=>setView('okur');get('ok-return').onclick=close;
 document.querySelectorAll('[data-open-okur]').forEach(b=>b.onclick=()=>{history.replaceState(null,'','#okur');open();});
 canvas.addEventListener('click',e=>{if(!active||view!=='atlas')return;const node=e.target.closest('.okur-atlas-node');if(node){e.stopImmediatePropagation();chooseNode(node.dataset.id);return;}const edge=e.target.closest('#okur-atlas-comparison [data-id]');if(edge){e.stopImmediatePropagation();routeId=edge.dataset.id;renderGraph();renderDetails();showDetails();}},true);
 document.addEventListener('click',e=>{if(!active)return;if(e.target.closest('[data-atlas-mode],#atlasBackHome,#resetBtn'))close();},true);
 canvas.addEventListener('click',e=>{if(active&&e.target===canvas){e.stopImmediatePropagation();selected=routeId=null;page=0;get('ok-select').value='';render();}},true);
 get('atlasNodeSearchInput')?.addEventListener('input',e=>{if(!active)return;e.stopImmediatePropagation();query=e.target.value.toLocaleLowerCase('ru');get('ok-search').value=e.target.value;selected=routeId=null;page=0;render();},true);
 window.addEventListener('resize',()=>{if(active){requestAnimationFrame(()=>{capture();render();});}else requestAnimationFrame(capture);});
 window.addEventListener('hashchange',()=>{if(location.hash==='#okur')open();else close();});document.addEventListener('keydown',e=>{if(active&&e.key==='Escape')close();});if(location.hash==='#okur')open();
})();
