(()=>{
 'use strict';
 const script=document.currentScript;
 const dataUrl=new URL('data.json?v=okur-1',script.src);
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const root=document.createElement('section');root.className='ok-layer';root.hidden=true;root.id='okur-layer';root.setAttribute('aria-label','Слой ОКУР');document.body.append(root);
 let data,loading,returnFocus,oldOverflow='',selected=null,family=null,routeId=null,page=0,zoom=1,view='map',extra=false;
 const byId=new Map();
 const get=id=>root.querySelector('#'+id);
 const group=id=>data.groups.find(g=>g.id===id);
 const gradeNames={DOCUMENTED_TRANSPORT:'Канал описан источником',MULTIPLE_DOCUMENTED_TRANSPORTS:'Несколько документированных каналов',DOCUMENTED_TRANSPORT_SCOPED:'Канал подтверждён в ограниченной области',DOCUMENTED_SHARED_SYSTEM_CONTEXT:'Совместное использование системы',MULTIPLE_SHARED_SYSTEM_CONTEXTS:'Несколько общих систем',MULTI_CHANNEL_DOCUMENTED:'Разные каналы для разных потоков',UNASSESSED:'Канал не оценён'};
 function shell(){root.innerHTML=`<header class="ok-header"><span class="ok-brand">РЭН</span><div class="ok-heading"><h1>ОКУР · общие публикации и подписки</h1><div class="ok-caption">Новый слой атласа · целевая архитектура</div></div><button class="ok-button" id="ok-close">Вернуться к карте РЭН</button></header><div class="ok-intro"><p>Ведомство подключается к ОКУР и публикует данные в согласованном виде. Получатели находят нужный продукт и получают разрешённые версии или изменения по подписке.</p><div class="ok-stats"><span><b>87</b>участников на карте</span><span><b>5</b>функций ОКУР</span><span><b>354</b>исходных связей в карточках</span></div><div class="ok-tabs"><button class="ok-button" id="ok-map-tab" aria-pressed="true">Структура для всех участников</button><button class="ok-button" id="ok-example-tab" aria-pressed="false">Как упрощается взаимодействие</button></div></div><div id="ok-content"></div><footer class="ok-footer">База связей: v203. Пять укрупнений: архив v212. Линии на новом слое показывают предлагаемые подключения к ОКУР; направления конкретных передач уточняются по исходным процессам.</footer>`;
 get('ok-close').onclick=close;get('ok-map-tab').onclick=()=>setView('map');get('ok-example-tab').onclick=()=>setView('example');setView(view);
 }
 function setView(next){view=next;get('ok-map-tab').setAttribute('aria-pressed',view==='map');get('ok-example-tab').setAttribute('aria-pressed',view==='example');if(view==='example'){example();return;}
 get('ok-content').innerHTML=`<div class="ok-layout"><aside class="ok-sidebar"><label class="ok-label" for="ok-search">Найти участника</label><input id="ok-search" class="ok-field" type="search" placeholder="Название ведомства…"><label class="ok-label" for="ok-select">Все участники</label><select id="ok-select" class="ok-field"><option value="">Общий вид · 87 участников</option>${data.nodes.map(n=>`<option value="${esc(n.id)}">${esc(n.name)}</option>`).join('')}</select><button id="ok-clear" class="ok-button ok-reset">Сбросить выбор</button><div class="ok-section-title">Функции ОКУР</div><div class="ok-family-list">${data.groups.map(g=>`<button class="ok-family" style="--family-color:${g.color}" data-family="${g.id}" aria-pressed="false"><strong>${g.id} · ${g.name}</strong><small>${g.count} исходных связей · ${g.nodeCount} участников</small></button>`).join('')}</div><p class="ok-small">Фильтр подсвечивает участников выбранного укрупнения. Цветные метки у узлов показывают состав их данных.</p><p class="ok-small">Одно подключение на участника — принцип проектируемой архитектуры. Число фактических интеграций и экономия пока не измерены.</p></aside><div class="ok-board"><div class="ok-toolbar"><span class="ok-small" id="ok-visible-count"></span><button class="ok-button" id="ok-minus" aria-label="Уменьшить карту">−</button><button class="ok-button" id="ok-plus" aria-label="Увеличить карту">+</button><button class="ok-button" id="ok-fit">По ширине</button></div><div class="ok-map-scroll" id="ok-map-scroll"><svg class="ok-map" id="ok-map" viewBox="0 0 1200 1540" role="group" aria-label="87 участников и пять функций ОКУР"></svg></div><p class="ok-small">Каждый узел имеет собственную точку подключения. Внутри ОКУР работают общие правила, каталоги и разрешённые продукты; владельцы данных сохраняются.</p></div><aside class="ok-detail"><div class="ok-detail-inner" id="ok-details" aria-live="polite"></div></aside></div>`;
 get('ok-search').oninput=()=>{selected=null;routeId=null;page=0;renderMap();renderDetails();};
 get('ok-select').onchange=e=>chooseNode(e.target.value||null);
 get('ok-clear').onclick=()=>{selected=family=routeId=null;page=0;get('ok-search').value='';get('ok-select').value='';render();};
 root.querySelectorAll('[data-family]').forEach(b=>b.onclick=()=>chooseFamily(b.dataset.family));
 get('ok-minus').onclick=()=>scale(-.25);get('ok-plus').onclick=()=>scale(.25);get('ok-fit').onclick=()=>{zoom=1;applyScale();};get('ok-select').value=selected||'';render();
 }
 function scale(delta){zoom=Math.min(3,Math.max(1,zoom+delta));applyScale();}
 function applyScale(){get('ok-map').style.width=zoom*100+'%';}
 function chooseNode(id){selected=id;routeId=null;page=0;get('ok-select').value=id||'';get('ok-search').value='';render();}
 function chooseFamily(id){family=family===id?null:id;routeId=null;page=0;render();}
 function render(){root.querySelectorAll('[data-family]').forEach(b=>{b.classList.toggle('active',b.dataset.family===family);b.setAttribute('aria-pressed',b.dataset.family===family);});renderMap();renderDetails();}
 function matchingNode(n){return (!family||n.families.includes(family))&&(!get('ok-search').value||n.name.toLocaleLowerCase('ru').includes(get('ok-search').value.toLocaleLowerCase('ru')));}
 function shortName(n){let s=n.name.replace(/Российской Федерации/g,'РФ').replace(/Федеральная служба по надзору в сфере здравоохранения \(Росздравнадзор\)/,'Росздравнадзор (полное наименование)').replace(/Федеральное агентство по управлению государственным имуществом \(Росимущество\)/,'Росимущество (полное наименование)').replace(/Федеральная служба по труду и занятости \(Роструд\)/,'Роструд (полное наименование)').replace(/Федеральный фонд обязательного медицинского страхования \(ФОМС\)/,'ФОМС');return s.length>34?s.slice(0,32)+'…':s;}
 function renderMap(){const svg=get('ok-map');let out=`<defs><marker id="ok-arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M0 0 L10 5 L0 10z" fill="#7d9271"/></marker></defs><rect x="365" y="54" width="470" height="1430" rx="20" fill="#edf0e5" stroke="#adbca8" stroke-width="2"/><text x="600" y="95" text-anchor="middle" font-size="29" fill="#3f5947" font-family="Georgia">ОКУР</text><text x="600" y="124" text-anchor="middle" font-size="16" fill="#6d7967">Общая среда · распределённые владельцы</text><path d="M385 150 V1445 M815 150 V1445" stroke="#9aae96" stroke-width="3" fill="none"/><text x="600" y="151" text-anchor="middle" font-size="13" fill="#6d7967">Точки подключения и согласование схем</text><rect x="420" y="190" width="360" height="66" rx="6" fill="#f8faf4" stroke="#ccd6c5"/><text x="600" y="218" text-anchor="middle" font-size="16" fill="#4c6650">Публиковать · находить · подписываться</text><text x="600" y="242" text-anchor="middle" font-size="13" fill="#6d7967">Роль выбирается отдельно для каждого продукта</text>`;
 data.groups.forEach((g,i)=>{const y=295+i*205;const active=!family||family===g.id;out+=`<g class="ok-service${active?'':' dim'}" data-service="${g.id}" tabindex="0" role="button" aria-label="${esc(g.id+' '+g.name)}"><title>${esc(g.description)}</title><rect x="415" y="${y}" width="370" height="154" rx="9" fill="#fff" stroke="${g.color}" stroke-width="${family===g.id?4:2}"/><text x="437" y="${y+30}" font-size="19" font-weight="600" fill="${g.color}">${g.id} · ${esc(g.name)}</text><text x="437" y="${y+62}" font-size="15" fill="#56634f">${esc(g.action)}</text><text x="437" y="${y+95}" font-size="14" fill="#6d7967">${g.count} исходных связей в укрупнении</text><text x="437" y="${y+123}" font-size="13" fill="#6d7967">${g.id==='A5'?'Общие правила для всех функций':'Выберите, чтобы изучить процессы'}</text></g>`;});
 out+=`<g fill="none" stroke="#7d9271" stroke-width="1.5" marker-end="url(#ok-arrow)"><path d="M600 449 V500"/><path d="M785 770 H800 V600 H785"/><path d="M785 975 H806 V610 H785"/></g><text x="610" y="478" font-size="12" fill="#65785b">Изменение версии</text><text x="600" y="685" text-anchor="middle" font-size="12" fill="#65785b">A3 → A2: уведомление о документе</text><text x="600" y="890" text-anchor="middle" font-size="12" fill="#65785b">A4 → A2: обновление показателя</text><path d="M415 1190 H398 V372 H415 M398 577 H415 M398 782 H415 M398 987 H415" fill="none" stroke="#9c9988" stroke-width="1.5" stroke-dasharray="4 4"/><text x="600" y="1360" text-anchor="middle" font-size="13" fill="#777969">A5: схемы, доступ и аудит для A1–A4</text><text x="600" y="1390" text-anchor="middle" font-size="16" fill="#4c6650">Публикация → разрешённый продукт</text><text x="600" y="1416" text-anchor="middle" font-size="16" fill="#4c6650">Подписка → нужные версии и изменения</text>`;
 const half=Math.ceil(data.nodes.length/2);data.nodes.forEach((n,i)=>{const left=i<half,row=left?i:i-half,y=190+row*28.5,x=left?338:862,port=left?385:815;const match=matchingNode(n);const isSelected=n.id===selected;const dot=n.core?'#417493':'#7f927b';out+=`<g class="ok-node${match?'':' dim'}${isSelected?' node-selected':''}" data-node="${esc(n.id)}" tabindex="0" role="button" aria-label="${esc(n.name)}"><title>${esc(n.name)} · ${n.routeCount} исходных связей · ${n.families.join(', ')}</title><path d="M${x} ${y} H${port}" stroke="${isSelected?'#286b93':'#b7c4ae'}" stroke-width="${isSelected?3:1.4}"/><circle cx="${port}" cy="${y}" r="2.5" fill="#83997d"/><circle class="node-dot" cx="${x}" cy="${y}" r="${n.core?7:5}" fill="${dot}"/><text class="node-label" x="${left?x-14:x+14}" y="${y+5}" text-anchor="${left?'end':'start'}" font-size="15" fill="#344e3d">${esc(shortName(n))}</text>${n.families.map((id,j)=>`<rect x="${left?x+10+j*6:x-14-j*6}" y="${y-3}" width="4" height="6" fill="${group(id).color}"/>`).join('')}</g>`;});svg.innerHTML=out;
 svg.querySelectorAll('[data-node]').forEach(el=>{el.onclick=()=>chooseNode(el.dataset.node);el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();chooseNode(el.dataset.node);}};});svg.querySelectorAll('[data-service]').forEach(el=>{el.onclick=()=>chooseFamily(el.dataset.service);el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();chooseFamily(el.dataset.service);}};});
 get('ok-visible-count').textContent=`На карте 87 узлов · выделено ${data.nodes.filter(matchingNode).length}`;applyScale();
 }
 function filteredRoutes(){const query=get('ok-search').value.toLocaleLowerCase('ru');return data.routes.filter(r=>(!selected||r.a===selected||r.b===selected)&&(!family||r.family===family)&&(!query||byId.get(r.a).name.toLocaleLowerCase('ru').includes(query)||byId.get(r.b).name.toLocaleLowerCase('ru').includes(query)));}
 function renderDetails(){const node=byId.get(selected),g=family&&group(family),routes=filteredRoutes();const picked=data.routes.find(r=>r.id===routeId);const pages=Math.max(1,Math.ceil(routes.length/12));page=Math.min(page,pages-1);
 let html=`<h2>${esc(node?.name||g?.name||'Структура ОКУР')}</h2>`;
 if(node){html+=`<p>Одна точка подключения к ОКУР. Состав продуктов и права на чтение определяются для каждого процесса отдельно.</p><div>${node.families.map(id=>`<span class="ok-chip">${id} · ${esc(group(id).name)}</span>`).join('')}</div>`;}
 else if(!g)html+=`<p>Владельцы публикуют согласованные продукты, а потребители используют их по разрешённым подпискам. Общие схемы и версии уменьшают повторную подготовку одинаковых данных.</p><p>На карте сохранены все 87 исходных узлов, включая классы участников и близкие наименования. Каждый имеет отдельную точку доступа.</p>`;
 if(g)html+=`<p><strong>${esc(g.action)}</strong></p><p>${esc(g.description)}</p>`;
 if(picked)html+=routeDetails(picked);
 html+=`<h3 class="ok-section-title">Исходные процессы · ${routes.length}</h3><p class="ok-small">Пары из атласа сохранены. Принадлежность к укрупнению сама по себе не доказывает возможность объединить данные в один продукт.</p><div>${routes.slice(page*12,page*12+12).map(r=>`<button class="ok-route${r.id===routeId?' active':''}" data-route="${esc(r.id)}"><small>${r.family} · ${esc(r.id)}</small>${esc(r.aName)} ↔ ${esc(r.bName)}<small>${esc(r.subject)}</small></button>`).join('')}</div><div class="ok-pages"><button class="ok-button" id="ok-prev" ${page===0?'disabled':''}>←</button><span class="ok-small">${page+1} / ${pages}</span><button class="ok-button" id="ok-next" ${page===pages-1?'disabled':''}>→</button></div>`;
 get('ok-details').innerHTML=html;root.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>{routeId=b.dataset.route;renderDetails();get('ok-details').scrollIntoView({block:'nearest'});});get('ok-prev').onclick=()=>{page--;renderDetails();};get('ok-next').onclick=()=>{page++;renderDetails();};
 }
 function routeDetails(r){const e=r.evidence;const sourceLinks=e.sources.filter(s=>/^https?:\/\//i.test(s.url||'')).map(s=>`<a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.title||s.id)}</a>`).join('');return `<div class="ok-evidence"><h3>${r.family} · ${esc(r.subject)}</h3><div class="ok-route-id">${esc(r.id)}</div><p><strong>Исходная связь:</strong> ${esc(r.aName)} ↔ ${esc(r.bName)}. Обозначение пары не задаёт направление передачи.</p><p><strong>Формат в архиве:</strong> ${esc(r.format||'не установлен')}</p><p><strong>Канал:</strong> ${esc(e.channels.join(', ')||'не установлен')}<br>${esc(gradeNames[e.grade]||'Ограничения подтверждения см. в описании источника')}</p>${e.scope?`<p>${esc(e.scope)}</p>`:''}${e.note?`<p>${esc(e.note)}</p>`:''}<p class="ok-small">${esc(e.date)}${e.environment?' · '+esc(e.environment):''}</p><p class="ok-small">${e.current2026?'В материалах проверки есть утверждение о работе в 2026 году; оно ограничено указанным потоком.':'Фактическая работа этого канала в 2026 году данной карточкой не подтверждается.'} Источники описывают существующую связь; ОКУР здесь предложен как будущая архитектура.</p>${sourceLinks}</div>`;}
 function example(){const consumers=['Росстат','Минэнерго России','Росздравнадзор','Росприроднадзор'];if(extra)consumers.push('Дополнительный разрешённый потребитель');get('ok-content').innerHTML=`<div class="ok-example"><h2>Подключение нового получателя не требует новой версии выдачи у источника</h2><p>Условный пример: нескольким ведомствам нужна одна и та же разрешённая версия сведений ЕГРЮЛ. В модели ниже сравнивается подготовка одинаковых выдач, а не число сообщений или существующих каналов.</p><label><input type="checkbox" id="ok-extra" ${extra?'checked':''}> Добавить ещё одного получателя</label><div class="ok-comparison"><section class="ok-example-card"><h3>Раздельная подготовка для каждого получателя</h3><p class="ok-small">Условный исходный сценарий с повторной подготовкой</p>${consumers.map(c=>`<div class="ok-example-row">ФНС → отдельная выдача → ${esc(c)}</div>`).join('')}<p><span class="ok-number">${consumers.length}</span> одинаковых выдач подготавливает источник</p></section><section class="ok-example-card"><h3>ОКУР: одна публикация, разрешённые подписки</h3><div class="ok-publication"><strong>ФНС · версия объекта ЕГРЮЛ</strong><br>A1: согласованная схема и актуальность<br>A5: назначение использования, права и аудит</div>${consumers.map(c=>`<div class="ok-example-row">A2 · разрешённая подписка → ${esc(c)}</div>`).join('')}<p><span class="ok-number">1</span> общую публикацию подготавливает источник</p><p class="ok-small">Доставки и проверки прав сохраняются для всех ${consumers.length} получателей. Для документов используется A3, для показателей — A4; эти функции не нужны для каждого потока одновременно.</p></section></div><p><strong>Условия повторного использования:</strong> совпадают объект, состав и версия сведений; права допускают использование; срок актуальности подходит всем получателям. Если условия различаются, нужны отдельные продукты или представления.</p><p class="ok-small">В атласе есть четыре связи ФНС с указанными ведомствами. Источники не доказывают, что сегодня выполняются четыре ручные подготовки одинаковой версии; это пояснение механизма ОКУР. Экономия для реальных процессов требует отдельной проверки.</p><button class="ok-button" id="ok-example-back">Открыть все 87 участников</button></div>`;get('ok-extra').onchange=e=>{extra=e.target.checked;example();};get('ok-example-back').onclick=()=>setView('map');}
 async function open(){if(!root.hidden)return;returnFocus=document.activeElement;oldOverflow=document.body.style.overflow;document.body.style.overflow='hidden';root.hidden=false;root.innerHTML='<p class="ok-error">Загрузка слоя ОКУР…</p>';try{if(!data){loading=loading||fetch(dataUrl,{cache:'no-cache'}).then(r=>{if(!r.ok)throw Error('HTTP '+r.status);return r.json();});data=await loading;if(data.nodes.length!==87||data.routes.length!==354)throw Error('Неполная база слоя');data.nodes.forEach(n=>byId.set(n.id,n));}if(root.hidden)return;shell();get('ok-close').focus();}catch(error){loading=null;root.innerHTML=`<div class="ok-error">Не удалось загрузить слой ОКУР. ${esc(error.message)}<p><button class="ok-button" id="ok-close-error">Вернуться к карте</button></p></div>`;get('ok-close-error').onclick=close;}}
 function close(){root.hidden=true;document.body.style.overflow=oldOverflow;if(location.hash==='#okur')history.replaceState(null,'',location.pathname+location.search);returnFocus?.focus();}
 document.querySelectorAll('[data-open-okur]').forEach(b=>b.addEventListener('click',()=>{history.replaceState(null,'','#okur');open();}));window.addEventListener('hashchange',()=>{if(location.hash==='#okur')open();else if(!root.hidden)close();});root.addEventListener('keydown',e=>{if(e.key==='Escape')close();});if(location.hash==='#okur')open();
})();
